# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

repos:
  CRAN: https://cloud.r-project.org
  USGS: https://owi.usgs.gov/R

env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
  
warnings_are_errors: true

r_github_packages:
  - jimhester/covr

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

script: 
  - |
    R CMD build . 
    travis_wait 20 R CMD check EGRET*tar.gz --as-cran

after_success:
  - if [[ "${R_CODECOV}" ]]; then travis_wait 20 R -e 'covr::coveralls()'; fi

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change

