# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages

matrix:
  include:
    - r: release
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      after_success: travis_wait 20 R -e 'covr::coveralls()'
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - r: devel

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

repos:
  CRAN: https://cloud.r-project.org
  USGS: https://owi.usgs.gov/R

env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
  
warnings_are_errors: true

r_github_packages:
  - jimhester/covr

script: 
  - |
    R CMD build . 
    travis_wait 20 R CMD check EGRET*tar.gz --as-cran


notifications:
  email:
    on_success: change
    on_failure: change

