<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Seasonal Analysis in EGRET • EGRET</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Seasonal Analysis in EGRET">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-53797708-7"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-53797708-7');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">EGRET</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.0.3.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/EGRET.html">Introduction</a>
</li>
<li>
  <a href="../reference/index.html">Function Help Pages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Enhancements.html">Enhancements</a>
    </li>
    <li>
      <a href="../articles/parallel.html">Running in Parallel</a>
    </li>
    <li>
      <a href="../articles/rResid.html">Random Residuals</a>
    </li>
    <li>
      <a href="../articles/SeasonalFraction.html">Seasonal Analysis</a>
    </li>
    <li>
      <a href="../articles/streamflow_trend.html">Daily Streamflow Trends</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Bibliograpy
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/References_WRTDS.html">WRTDS</a>
    </li>
    <li>
      <a href="../articles/References_Extend.html">Extending Methods</a>
    </li>
    <li>
      <a href="../articles/References_Region.html">Regional Studies</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/USGS-R/EGRET">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Seasonal Analysis in EGRET</h1>
                        <h4 class="author">Robert M. Hirsch and Laura DeCicco</h4>
            
            <h4 class="date">2019-10-02</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/USGS-R/EGRET/blob/master/vignettes/SeasonalFraction.Rmd"><code>vignettes/SeasonalFraction.Rmd</code></a></small>
      <div class="hidden name"><code>SeasonalFraction.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>This document describes how to obtain seasonal information from the R package <a href="https://CRAN.R-project.org/package=EGRET">EGRET</a>. For example, we might want to know the fraction of the load that takes place in the winter season (say that is December, January, and February). We can look at the seasonal information for a single year, or averages over several years, or in terms of flow normalized fluxes.</p>
</div>
<div id="getting-started" class="section level1">
<h1 class="hasAnchor">
<a href="#getting-started" class="anchor"></a>Getting started</h1>
<p>First, you need to have installed and loaded the <code>EGRET</code> package. Then, you’ll need need to create an <code>eList</code> object. See the <code>EGRET</code> vignette or user guide <a href="http://pubs.usgs.gov/tm/04/a10/">here</a> for more information on how to use your own water quality data in <code>EGRET</code>. Once the <code>eList</code> object has been created, run the <code>modelEstimation</code> function to create a WRTDS model.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(EGRET)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(dplyr)</a>
<a class="sourceLine" id="cb1-3" title="3">eList &lt;-<span class="st"> </span>Choptank_eList</a></code></pre></div>
<p>For this post, we will use the Choptank River, measuring Inorganic nitrogen (nitrate and nitrite) as an example.</p>
<p>To start with lets look at the results calculated for complete water years.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">water_year &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableResults.html">tableResults</a></span>(eList)</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Water Year 
## 
##    Year   Discharge    Conc    FN_Conc     Flux    FN_Flux
##              cms            mg/L             10^6 kg/yr 
## 
##    1980      4.25     0.949     1.003    0.1154     0.106
##    1981      2.22     1.035     0.999    0.0675     0.108
##    1982      3.05     1.036     0.993    0.0985     0.110
##    1983      4.99     1.007     0.993    0.1329     0.112
##    1984      5.72     0.990     1.002    0.1597     0.114
##    1985      1.52     1.057     1.017    0.0489     0.116
##    1986      2.63     1.062     1.038    0.0903     0.119
##    1987      3.37     1.079     1.062    0.1142     0.122
##    1988      1.87     1.120     1.085    0.0660     0.125
##    1989      5.61     1.055     1.105    0.1638     0.127
##    1990      4.01     1.115     1.125    0.1349     0.129
##    1991      2.75     1.172     1.143    0.0980     0.130
##    1992      2.19     1.203     1.159    0.0810     0.132
##    1993      3.73     1.215     1.173    0.1306     0.132
##    1994      5.48     1.144     1.187    0.1634     0.133
##    1995      2.41     1.266     1.201    0.0928     0.134
##    1996      6.24     1.134     1.213    0.1980     0.135
##    1997      5.83     1.180     1.221    0.1884     0.136
##    1998      4.88     1.236     1.229    0.1593     0.137
##    1999      2.90     1.277     1.238    0.0919     0.138
##    2000      4.72     1.213     1.253    0.1627     0.139
##    2001      4.88     1.251     1.268    0.1655     0.140
##    2002      1.24     1.321     1.285    0.0483     0.141
##    2003      8.64     1.140     1.303    0.2664     0.143
##    2004      5.28     1.274     1.321    0.1832     0.144
##    2005      3.81     1.360     1.341    0.1444     0.146
##    2006      3.59     1.382     1.362    0.1409     0.147
##    2007      4.28     1.408     1.382    0.1593     0.149
##    2008      2.56     1.477     1.401    0.1008     0.149
##    2009      3.68     1.409     1.419    0.1328     0.149
##    2010      7.19     1.323     1.438    0.2236     0.149
##    2011      5.24     1.438     1.457    0.1554     0.148</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">water_year_<span class="dv">2010</span>_flux &lt;-<span class="st"> </span>water_year<span class="op">$</span><span class="st">`</span><span class="dt">FN Flux [10^6kg/yr]</span><span class="st">`</span>[water_year<span class="op">$</span>Year <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>]</a></code></pre></div>
<p>Looking at the last column of these results we see that, for example, the flow normalized flux in water year 2010 is estimated to be 0.149 10<sup>6</sup> kg/year. Now, let’s say we had a particular interest in the winter season which we define here as the months of December, January, and February.</p>
<p>The next step is to establish what season you are interested in looking at. All functions in <code>EGRET</code> can be done on the “water year” (Oct-Sept), the calendar year (Jan-Dec), or any set of sequential months. To define what period of analysis (PA) to use, there is a function <code>setPA</code>. The <code>setPA</code> function has two arguments:</p>
<ul>
<li>
<code>paStart</code> is the number of the calendar month that is the start of the season.<br>
</li>
<li>
<code>paLong</code> is the length of the season in months (it can be any number from 1 to 12).</li>
</ul>
<p>For example let’s say we want to consider the winter, defined here as December through February, the starting month (<code>paStart</code>) would be 12, and the length (<code>paLong</code>) would be 3:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">eList &lt;-<span class="st"> </span><span class="kw"><a href="../reference/setPA.html">setPA</a></span>(eList, <span class="dt">paStart =</span> <span class="dv">12</span>, <span class="dt">paLong =</span> <span class="dv">3</span>)</a></code></pre></div>
<p>Now lets view our results when we are focusing on the winter season.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1">winter &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableResults.html">tableResults</a></span>(eList)</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Season Consisting of Dec Jan Feb 
## 
##    Year   Discharge    Conc    FN_Conc     Flux    FN_Flux
##              cms            mg/L             10^6 kg/yr 
## 
##    1980     4.220      1.10      1.11    0.1403     0.156
##    1981     1.960      1.20      1.13    0.0735     0.161
##    1982     5.057      1.16      1.15    0.1764     0.165
##    1983     3.504      1.21      1.16    0.1310     0.169
##    1984     8.437      1.12      1.18    0.2624     0.173
##    1985     2.249      1.24      1.21    0.0884     0.177
##    1986     5.087      1.25      1.24    0.1902     0.182
##    1987     7.730      1.23      1.27    0.2707     0.187
##    1988     2.590      1.29      1.29    0.1039     0.191
##    1989     3.327      1.36      1.31    0.1400     0.193
##    1990     4.609      1.35      1.33    0.1928     0.195
##    1991     3.883      1.36      1.33    0.1559     0.196
##    1992     2.303      1.40      1.33    0.1015     0.195
##    1993     4.421      1.36      1.32    0.1877     0.194
##    1994     5.849      1.31      1.31    0.2072     0.193
##    1995     3.693      1.37      1.31    0.1543     0.192
##    1996     7.151      1.29      1.31    0.2618     0.193
##    1997    11.786      1.18      1.32    0.3718     0.193
##    1998     9.308      1.27      1.32    0.2979     0.194
##    1999     2.526      1.32      1.33    0.1091     0.196
##    2000     4.785      1.39      1.35    0.1995     0.198
##    2001     5.392      1.39      1.37    0.2194     0.200
##    2002     0.824      1.29      1.39    0.0336     0.202
##    2003     9.213      1.33      1.41    0.3186     0.204
##    2004     8.653      1.35      1.44    0.3126     0.207
##    2005     4.196      1.54      1.47    0.1978     0.211
##    2006     5.843      1.51      1.51    0.2675     0.214
##    2007     5.417      1.55      1.53    0.2419     0.216
##    2008     2.436      1.62      1.55    0.1217     0.217
##    2009     2.711      1.66      1.56    0.1396     0.216
##    2010    13.779      1.26      1.57    0.4161     0.215
##    2011     3.369      1.66      1.57    0.1669     0.215</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1">winter_<span class="dv">2010</span>_flux &lt;-<span class="st"> </span>winter<span class="op">$</span><span class="st">`</span><span class="dt">FN Flux [10^6kg/yr]</span><span class="st">`</span>[winter<span class="op">$</span>Year <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>]</a>
<a class="sourceLine" id="cb8-2" title="2"></a>
<a class="sourceLine" id="cb8-3" title="3">filter_setPA &lt;-<span class="st"> </span><span class="cf">function</span>(Daily, paStart, paLong){</a>
<a class="sourceLine" id="cb8-4" title="4">  </a>
<a class="sourceLine" id="cb8-5" title="5">  monthsToUse &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="dt">from =</span> paStart, </a>
<a class="sourceLine" id="cb8-6" title="6">                     <span class="dt">by =</span> <span class="dv">1</span>,</a>
<a class="sourceLine" id="cb8-7" title="7">                     <span class="dt">length.out =</span> paLong)</a>
<a class="sourceLine" id="cb8-8" title="8">  monthsToUse[monthsToUse <span class="op">&gt;</span><span class="st"> </span><span class="dv">12</span>] &lt;-<span class="st"> </span>monthsToUse[monthsToUse <span class="op">&gt;</span><span class="st"> </span><span class="dv">12</span>] <span class="op">-</span><span class="st"> </span><span class="dv">12</span> </a>
<a class="sourceLine" id="cb8-9" title="9">  </a>
<a class="sourceLine" id="cb8-10" title="10">  Daily_filtered &lt;-<span class="st"> </span>Daily <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-11" title="11"><span class="st">    </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(Month <span class="op">%in%</span><span class="st"> </span>monthsToUse) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-12" title="12"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">YearIndex =</span> <span class="kw"><a href="https://rdrr.io/r/base/Round.html">trunc</a></span>(DecYear))</a>
<a class="sourceLine" id="cb8-13" title="13">  </a>
<a class="sourceLine" id="cb8-14" title="14">  crossesYear &lt;-<span class="st"> </span>paLong <span class="op">+</span><span class="st"> </span>(paStart <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">&gt;</span><span class="st"> </span><span class="dv">12</span></a>
<a class="sourceLine" id="cb8-15" title="15">  </a>
<a class="sourceLine" id="cb8-16" title="16">  <span class="cf">if</span>(crossesYear){</a>
<a class="sourceLine" id="cb8-17" title="17">    Daily_filtered<span class="op">$</span>YearIndex[Daily_filtered<span class="op">$</span>Month <span class="op">&gt;=</span><span class="st"> </span>paStart] &lt;-</a>
<a class="sourceLine" id="cb8-18" title="18"><span class="st">      </span>Daily_filtered<span class="op">$</span>YearIndex[Daily_filtered<span class="op">$</span>Month <span class="op">&gt;=</span><span class="st"> </span>paStart] <span class="op">+</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb8-19" title="19">  }</a>
<a class="sourceLine" id="cb8-20" title="20">  </a>
<a class="sourceLine" id="cb8-21" title="21">  get_years &lt;-<span class="st"> </span>Daily_filtered <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-22" title="22"><span class="st">    </span><span class="kw">group_by</span>(YearIndex) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-23" title="23"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">Year =</span> <span class="kw"><a href="https://rdrr.io/r/base/Round.html">trunc</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DecYear))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-24" title="24"><span class="st">    </span><span class="kw">ungroup</span>() </a>
<a class="sourceLine" id="cb8-25" title="25">    </a>
<a class="sourceLine" id="cb8-26" title="26"></a>
<a class="sourceLine" id="cb8-27" title="27">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(get_years)</a>
<a class="sourceLine" id="cb8-28" title="28">  </a>
<a class="sourceLine" id="cb8-29" title="29">}</a>
<a class="sourceLine" id="cb8-30" title="30"></a>
<a class="sourceLine" id="cb8-31" title="31">number_of_days &lt;-<span class="st"> </span>eList<span class="op">$</span>Daily <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-32" title="32"><span class="st">  </span><span class="kw">filter_setPA</span>(<span class="dt">paStart =</span> eList<span class="op">$</span>INFO<span class="op">$</span>paStart,</a>
<a class="sourceLine" id="cb8-33" title="33">               <span class="dt">paLong =</span> eList<span class="op">$</span>INFO<span class="op">$</span>paLong) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-34" title="34"><span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-35" title="35"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n_days =</span> <span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(Q)))</a>
<a class="sourceLine" id="cb8-36" title="36"></a>
<a class="sourceLine" id="cb8-37" title="37">number_of_days_<span class="dv">2010</span> &lt;-<span class="st"> </span>number_of_days<span class="op">$</span>n_days[number_of_days<span class="op">$</span>Year <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>]</a></code></pre></div>
<p>Note that now the estimated flow normalized flux is 0.215 10<sup>6</sup> kg/year. Let’s take a moment to think about that in relation to the previous result. What it is saying is that the flux (mass per unit time) is greater during this three month period that the average flux for the entire water year. That makes sense, some seasons will have higher than average fluxes and other seasons will have lower than average fluxes.</p>
<p>Now, it might be that we want to think about these results, not in terms of a flux but in terms of mass alone. In the first result (water year) the mass for the year is 0.149 10<sup>6</sup> kg. But for the winter season we would compute the mass as 0.215 * 90 / 365 to give us a result of 0.053 10<sup>6</sup> kg. To get this result we took the annual rate (0.215) and divided by the number of days in the year (365) to get a rate in mass per day and then multiplied by the number of days in the season (90) which is the sum of the length of those three months to simply get a total mass.</p>
<p>We have taken pains here to run through this calculation because users have sometimes been confused, wondering how the flux for a part of the year can be greater than the flux for the whole year. Depending on the ultimate objective of the analysis one might want to present the seasonal results in either of these ways (mass or mass per unit time).</p>
<p>Next we will look at descriptions of change.</p>
</div>
<div id="seasonal-changes" class="section level1">
<h1 class="hasAnchor">
<a href="#seasonal-changes" class="anchor"></a>Seasonal Changes</h1>
<p>Let’s use the tableChange function to explore the change from 1990 to 2010. We will do it first for the full water year and then for the winter season.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">eList &lt;-<span class="st"> </span><span class="kw"><a href="../reference/setPA.html">setPA</a></span>(eList, <span class="dt">paStart =</span> <span class="dv">12</span>, <span class="dt">paLong =</span> <span class="dv">12</span>)</a>
<a class="sourceLine" id="cb9-2" title="2">change_annual_flux &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableChange.html">tableChangeSingle</a></span>(eList, <span class="dt">flux =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb9-3" title="3">                                   <span class="dt">yearPoints =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1990</span>,<span class="dv">2010</span>))</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Year Starting With December 
## 
## 
## 
##                  Flux Trends
##    time span          change        slope       change        slope
##                  10^6 kg/yr   10^6 kg/yr/yr      %         %/yr
## 
##  1990  to  2010         0.02      0.00099           15         0.77</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">change_annual_conc &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableChange.html">tableChangeSingle</a></span>(eList, <span class="dt">flux =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb11-2" title="2">                                   <span class="dt">yearPoints =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1990</span>,<span class="dv">2010</span>))</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Year Starting With December 
## 
##            Concentration trends
##    time span       change     slope    change     slope
##                      mg/L   mg/L/yr        %       %/yr
## 
##  1990  to  2010      0.32     0.016        28       1.4</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">eList &lt;-<span class="st"> </span><span class="kw"><a href="../reference/setPA.html">setPA</a></span>(eList, <span class="dt">paStart =</span> <span class="dv">12</span>, <span class="dt">paLong =</span> <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb13-2" title="2">change_season_flux &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableChange.html">tableChangeSingle</a></span>(eList, <span class="dt">flux =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb13-3" title="3">                                   <span class="dt">yearPoints =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1990</span>,<span class="dv">2010</span>))</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Season Consisting of Dec Jan Feb 
## 
## 
## 
##                  Flux Trends
##    time span          change        slope       change        slope
##                  10^6 kg/yr   10^6 kg/yr/yr      %         %/yr
## 
##  1990  to  2010         0.02        0.001           10         0.51</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">change_season_conc &lt;-<span class="st"> </span><span class="kw"><a href="../reference/tableChange.html">tableChangeSingle</a></span>(eList, <span class="dt">flux =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb15-2" title="2">                                   <span class="dt">yearPoints =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1990</span>,<span class="dv">2010</span>))</a></code></pre></div>
<pre><code>## 
##    Choptank River 
##    Inorganic nitrogen (nitrate and nitrite)
##    Season Consisting of Dec Jan Feb 
## 
##            Concentration trends
##    time span       change     slope    change     slope
##                      mg/L   mg/L/yr        %       %/yr
## 
##  1990  to  2010      0.24     0.012        18      0.89</code></pre>
<p>What we see is a fairly large difference between the concentration trends for the winter as compared to the whole year (concentration rose more steeply for the winter than it did for the year on average). But what we are going to focus on here is the trend in flux. The first thing to note is that the change from 1990 to 2010 is identical for the winter season and the year as a whole. That is, the change in the flow normalized flux for the full water year is 0.02 10<sup>6</sup> kg/year (it went from 0.129 to 0.149) and then, when we look at the winter season the change is also 0.02 10<sup>6</sup> kg/yr (from 0.195 to 0.215). So the change for this season over the 20 year period is essentially the same as the change for the entire water year. In other words, the results tell us that although the change in flux (mass per unit time) for the winter is the same as for the full year, the change in the mass for the winter season is about 25% of the change for the full year (because the winter consists of about 25% of the days in the year). Thus, we can conclude that the winter change is not atypical of the changes for the other parts of the year.</p>
<p>The results shown above also express the change as a slope (either 0.00099 or 0.001 virtually identical to each other) and these are simply the change results divided by the number of years. The next entry in the <code>tableChange</code> output is for change expressed as %. Here we see a big difference between the winter and the whole year. The whole year shows an increase of 15 % over the 20 years, while the winter season shows an increase of 10 %. That is because the same amount of increase 0.02 10<sup>6</sup> kg / year is being compared to a the smaller number (1990 flow normalized annual flux of 0.129 10<sup>6</sup> kg/year) in the first table and compared to a larger number (seasonal flux of 0.195 10<sup>6</sup> kg/year) in the second table. So, even though the change is focused equally in the winter and non-winter months, the percentage change for the winter is smaller than the percentage change for the whole year.</p>
</div>
<div id="seasonal-load-fraction" class="section level1">
<h1 class="hasAnchor">
<a href="#seasonal-load-fraction" class="anchor"></a>Seasonal Load Fraction</h1>
<p>Next, we can think about the seasonal load fraction.</p>
<p>You will need to read in two new functions called <code>setupSeasons</code> and <code>setupYearsPlus</code> designed for this purpose. You can copy them from here and paste them into your workspace (all as a single copy and paste) or you can create an .R file from them that you will source each time you want to use them. The functions use the package <a href="https://CRAN.R-project.org/package=dplyr"><code>dplyr</code></a>, a package that is useful for general data exploration and manipulation.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">setupSeasons &lt;-<span class="st"> </span><span class="cf">function</span>(eList){</a>
<a class="sourceLine" id="cb17-2" title="2">  </a>
<a class="sourceLine" id="cb17-3" title="3">  Daily &lt;-<span class="st"> </span>eList<span class="op">$</span>Daily</a>
<a class="sourceLine" id="cb17-4" title="4">  </a>
<a class="sourceLine" id="cb17-5" title="5">  paLong &lt;-<span class="st"> </span>eList<span class="op">$</span>INFO<span class="op">$</span>paLong</a>
<a class="sourceLine" id="cb17-6" title="6">  paStart &lt;-<span class="st"> </span>eList<span class="op">$</span>INFO<span class="op">$</span>paStart</a>
<a class="sourceLine" id="cb17-7" title="7">  </a>
<a class="sourceLine" id="cb17-8" title="8">  Daily_season &lt;-<span class="st"> </span><span class="kw">filter_setPA</span>(Daily,</a>
<a class="sourceLine" id="cb17-9" title="9">                               <span class="dt">paStart =</span> paStart,</a>
<a class="sourceLine" id="cb17-10" title="10">                               <span class="dt">paLong =</span> paLong)</a>
<a class="sourceLine" id="cb17-11" title="11">  Daily_annual &lt;-<span class="st"> </span><span class="kw">filter_setPA</span>(Daily,</a>
<a class="sourceLine" id="cb17-12" title="12">                               <span class="dt">paStart =</span> paStart,</a>
<a class="sourceLine" id="cb17-13" title="13">                               <span class="dt">paLong =</span> <span class="dv">12</span>)</a>
<a class="sourceLine" id="cb17-14" title="14"></a>
<a class="sourceLine" id="cb17-15" title="15">  <span class="co">#Cleanup units:</span></a>
<a class="sourceLine" id="cb17-16" title="16">  divideBy &lt;-<span class="st"> </span><span class="dv">1000000</span></a>
<a class="sourceLine" id="cb17-17" title="17">  divideBy &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb17-18" title="18"></a>
<a class="sourceLine" id="cb17-19" title="19">  <span class="co"># Convert flux to kg/year</span></a>
<a class="sourceLine" id="cb17-20" title="20">  unit_scale &lt;-<span class="st"> </span>fluxConst[[<span class="dv">9</span>]]<span class="op">@</span>unitFactor <span class="op">/</span><span class="st"> </span>divideBy</a>
<a class="sourceLine" id="cb17-21" title="21">  </a>
<a class="sourceLine" id="cb17-22" title="22">  SeasonResults &lt;-<span class="st"> </span>Daily_season <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb17-23" title="23"><span class="st">      </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb17-24" title="24"><span class="st">      </span><span class="kw">summarize</span>(<span class="dt">DecYear =</span> <span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DecYear),</a>
<a class="sourceLine" id="cb17-25" title="25">                <span class="dt">Counts =</span> <span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(ConcDay)),</a>
<a class="sourceLine" id="cb17-26" title="26">                <span class="dt">Flux =</span> <span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(FluxDay) <span class="op">*</span><span class="st"> </span>unit_scale,</a>
<a class="sourceLine" id="cb17-27" title="27">                <span class="dt">FNFlux =</span> <span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(FNFlux) <span class="op">*</span><span class="st"> </span>unit_scale)</a>
<a class="sourceLine" id="cb17-28" title="28">  </a>
<a class="sourceLine" id="cb17-29" title="29">  AnnualResults &lt;-<span class="st"> </span>Daily_annual <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-30" title="30"><span class="st">    </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb17-31" title="31"><span class="st">    </span><span class="kw">summarize</span>(<span class="dt">AnnualCounts =</span> <span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(ConcDay)),</a>
<a class="sourceLine" id="cb17-32" title="32">              <span class="dt">AnnualFlux =</span> <span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(FluxDay) <span class="op">*</span><span class="st"> </span>unit_scale,</a>
<a class="sourceLine" id="cb17-33" title="33">              <span class="dt">AnnualFNFlux =</span> <span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(FNFlux) <span class="op">*</span><span class="st"> </span>unit_scale) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-34" title="34"><span class="st">    </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(AnnualCounts <span class="op">&gt;=</span><span class="st"> </span><span class="dv">365</span>)</a>
<a class="sourceLine" id="cb17-35" title="35">    </a>
<a class="sourceLine" id="cb17-36" title="36"></a>
<a class="sourceLine" id="cb17-37" title="37">  seasonPctResults &lt;-<span class="st"> </span>SeasonResults <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-38" title="38"><span class="st">    </span><span class="kw">select</span>(DecYear, Year, Flux, FNFlux, Counts) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb17-39" title="39"><span class="st">    </span><span class="kw">left_join</span>(<span class="kw">select</span>(AnnualResults,</a>
<a class="sourceLine" id="cb17-40" title="40">                     Year, AnnualCounts,</a>
<a class="sourceLine" id="cb17-41" title="41">                     AnnualFlux, AnnualFNFlux), <span class="dt">by=</span><span class="st">"Year"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-42" title="42"><span class="st">      </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(<span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(AnnualFlux)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-43" title="43"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">pctFlux =</span> <span class="dv">100</span><span class="op">*</span>Flux<span class="op">*</span>Counts<span class="op">/</span>(AnnualFlux<span class="op">*</span>AnnualCounts),</a>
<a class="sourceLine" id="cb17-44" title="44">           <span class="dt">pctFNFlux =</span> <span class="dv">100</span><span class="op">*</span>FNFlux<span class="op">*</span>Counts<span class="op">/</span>(AnnualFNFlux<span class="op">*</span>AnnualCounts)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-45" title="45"><span class="st">    </span><span class="kw">rename</span>(<span class="dt">SeasonFlux =</span> Flux,</a>
<a class="sourceLine" id="cb17-46" title="46">           <span class="dt">SeasonFNFlux =</span> FNFlux)</a>
<a class="sourceLine" id="cb17-47" title="47">  </a>
<a class="sourceLine" id="cb17-48" title="48">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(seasonPctResults)</a>
<a class="sourceLine" id="cb17-49" title="49">}</a></code></pre></div>
<p>Simply use the loaded <code>eList</code> to calculate these seasonal load fractions. Let’s go back to the winter season (Dec-Feb):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1">eList &lt;-<span class="st"> </span><span class="kw"><a href="../reference/setPA.html">setPA</a></span>(eList, <span class="dt">paStart =</span> <span class="dv">12</span>, <span class="dt">paLong =</span> <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb18-2" title="2">seasonPctResults &lt;-<span class="st"> </span><span class="kw">setupSeasons</span>(eList)</a></code></pre></div>
</div>
<div id="looking-at-your-results" class="section level1">
<h1 class="hasAnchor">
<a href="#looking-at-your-results" class="anchor"></a>Looking at your results</h1>
<p>What you now have is a data frame called <code>seasonPctResults</code>. The columns it contains are the following:</p>
<table class="table">
<colgroup>
<col width="20%">
<col width="80%">
</colgroup>
<thead><tr class="header">
<th>variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>DecYear</td>
<td>Decimal Year of the mid-date of the season</td>
</tr>
<tr class="even">
<td>Year</td>
<td>Calendar Year of mid-date of the year</td>
</tr>
<tr class="odd">
<td>AnnualFlux</td>
<td>Estimated flux for the water year in millions of kg</td>
</tr>
<tr class="even">
<td>AnnualFNFlux</td>
<td>Flow Normalized flux for the water year in millions of kg</td>
</tr>
<tr class="odd">
<td>SeasonFlux</td>
<td>Estimated flux for the season in millions of kg</td>
</tr>
<tr class="even">
<td>SeasonFNFlux</td>
<td>Flow Normalized flux for the season in millions of kg</td>
</tr>
<tr class="odd">
<td>pctFlux</td>
<td>Season flux as a percentage of Annual Flux</td>
</tr>
<tr class="even">
<td>pctFNFlux</td>
<td>FlowNormalized Seasonal Flux as a percent of Flow Normalized Annual Flux</td>
</tr>
</tbody>
</table>
</div>
<div id="plotting-the-time-series" class="section level1">
<h1 class="hasAnchor">
<a href="#plotting-the-time-series" class="anchor"></a>Plotting the time series</h1>
<p>We can make a graph showing the percentage flux (estimated annual and flow normalized). Note, this workflow uses base R plotting functions. You could also use the <code>EGRET</code> function <code>genericEGRETDotPlot</code> to automatically to pick some plotting styles that are consistent with other <code>EGRET</code> plots.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">plotTitle =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(<span class="st">"Seasonal Flux as a Percent of Annual Flux</span><span class="ch">\n</span><span class="st">"</span>,</a>
<a class="sourceLine" id="cb19-2" title="2">                  eList<span class="op">$</span>INFO<span class="op">$</span>shortName, eList<span class="op">$</span>INFO<span class="op">$</span>paramShortName,</a>
<a class="sourceLine" id="cb19-3" title="3">                  <span class="st">"</span><span class="ch">\n</span><span class="st">Solid line is percentage of flow normalized flux"</span>) </a>
<a class="sourceLine" id="cb19-4" title="4"><span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">mar=</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dt">mgp=</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">0</span>))</a>
<a class="sourceLine" id="cb19-5" title="5"><span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(seasonPctResults<span class="op">$</span>DecYear, seasonPctResults<span class="op">$</span>pctFlux,<span class="dt">pch=</span><span class="dv">20</span>,</a>
<a class="sourceLine" id="cb19-6" title="6">     <span class="dt">yaxs=</span><span class="st">"i"</span>,<span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="dv">100</span>),<span class="dt">las=</span><span class="dv">1</span>,<span class="dt">tck=</span>.<span class="dv">01</span>,</a>
<a class="sourceLine" id="cb19-7" title="7">     <span class="dt">xlab=</span><span class="st">"Year"</span>,<span class="dt">ylab=</span><span class="st">"Percentage of Annual Flux"</span>,</a>
<a class="sourceLine" id="cb19-8" title="8">     <span class="dt">main=</span>plotTitle,<span class="dt">cex=</span><span class="fl">1.5</span>)</a>
<a class="sourceLine" id="cb19-9" title="9"><span class="kw"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(seasonPctResults<span class="op">$</span>DecYear,seasonPctResults<span class="op">$</span>pctFNFlux,<span class="dt">col=</span><span class="st">"green"</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb19-10" title="10"><span class="kw"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span>(<span class="dv">3</span>, <span class="dt">labels =</span> <span class="ot">FALSE</span>,<span class="dt">tck=</span>.<span class="dv">01</span>)</a>
<a class="sourceLine" id="cb19-11" title="11"><span class="kw"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span>(<span class="dv">4</span>, <span class="dt">labels =</span> <span class="ot">FALSE</span>,<span class="dt">tck=</span>.<span class="dv">01</span>)</a></code></pre></div>
<div class="figure">
<img src="SeasonalFraction_files/figure-html/unnamed-chunk-7-1.png" alt="Seasonal flux as a percentage of annual flux." width="700"><p class="caption">
Seasonal flux as a percentage of annual flux.
</p>
</div>
<p>We can interpret this example graph as follows. The winter flux of Inorganic nitrogen (nitrate and nitrite) fluctuates a good deal from year to year. From a low of around 10% to a high of around 60% but the mean percentage hasn’t changed much over the years. It is around 35% of the annual total flux.</p>
</div>
<div id="computing-averages-over-a-period-of-years" class="section level1">
<h1 class="hasAnchor">
<a href="#computing-averages-over-a-period-of-years" class="anchor"></a>Computing averages over a period of years</h1>
<p>Let’s say we wanted to answer the question, what percentage of the annual total flux moved in the winter season during the years 2000 through 2010. We can answer that question with a simple set of calculations.</p>
<p>Keep in mind, the way we are defining “year” is what year the ending year of the period of anaylsis fell. So, for this analysis, the full 2010 “year” is from Dec. 2009 through the end of November 2010.</p>
<ul>
<li><p>Filter the data frame <code>seasonPctResults</code> for the years 2000 - 2010.</p></li>
<li><p>Now we can compute the sum of the annual fluxes for those years and the sum of the seasonal fluxes for those years, and then get our answer by taking the ratio and multiplying by 100.</p></li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1">years00_<span class="dv">10</span> &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(seasonPctResults, Year <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2000</span>, Year <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2010</span>)</a>
<a class="sourceLine" id="cb20-2" title="2"></a>
<a class="sourceLine" id="cb20-3" title="3">sumYears &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(years00_<span class="dv">10</span><span class="op">$</span>AnnualFlux)</a>
<a class="sourceLine" id="cb20-4" title="4"> </a>
<a class="sourceLine" id="cb20-5" title="5">sumSeasons &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(years00_<span class="dv">10</span><span class="op">$</span>SeasonFlux <span class="op">*</span><span class="st"> </span>years00_<span class="dv">10</span><span class="op">$</span>Counts <span class="op">/</span></a>
<a class="sourceLine" id="cb20-6" title="6"><span class="st">                    </span>years00_<span class="dv">10</span><span class="op">$</span>AnnualCounts)</a>
<a class="sourceLine" id="cb20-7" title="7"></a>
<a class="sourceLine" id="cb20-8" title="8">avePct &lt;-<span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span>sumSeasons <span class="op">/</span><span class="st"> </span>sumYears</a></code></pre></div>
<p>The total flux for all years in the period of interest in millions of kg is <code>sumYears</code> = 1.73.</p>
<p>The total seasonal flux for all years of the period of interest in millions of kg is <code>sumSeasons</code> = 0.61.</p>
<p>The percentage of the total flux for the years 2000 through 2010 that was transported in the winter months is <code>avePct</code> = 35.3.</p>
<p>This can be determined for any set of years simply by changing <code>Year</code> values in the <code><a href="https://rdrr.io/pkg/dplyr/man/filter.html">dplyr::filter</a></code> function. So, for the years 1990-1999:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">years90_<span class="dv">99</span> &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(seasonPctResults, Year <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1990</span>, Year <span class="op">&lt;=</span><span class="st"> </span><span class="dv">1999</span>)</a>
<a class="sourceLine" id="cb21-2" title="2"></a>
<a class="sourceLine" id="cb21-3" title="3"><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"sumYears"</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(years90_<span class="dv">99</span><span class="op">$</span>AnnualFlux),</a>
<a class="sourceLine" id="cb21-4" title="4"><span class="st">"sumSeasons"</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(years90_<span class="dv">99</span><span class="op">$</span>SeasonFlux <span class="op">*</span><span class="st"> </span>years90_<span class="dv">99</span><span class="op">$</span>Counts <span class="op">/</span><span class="st"> </span>years90_<span class="dv">99</span><span class="op">$</span>AnnualCounts),</a>
<a class="sourceLine" id="cb21-5" title="5"><span class="st">"avePct"</span> =<span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span>sumSeasons <span class="op">/</span><span class="st"> </span>sumYears)</a></code></pre></div>
<pre><code>##   sumYears sumSeasons     avePct 
##  1.3327152  0.5037539 35.2611821</code></pre>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#getting-started">Getting started</a></li>
      <li><a href="#seasonal-changes">Seasonal Changes</a></li>
      <li><a href="#seasonal-load-fraction">Seasonal Load Fraction</a></li>
      <li><a href="#looking-at-your-results">Looking at your results</a></li>
      <li><a href="#plotting-the-time-series">Plotting the time series</a></li>
      <li><a href="#computing-averages-over-a-period-of-years">Computing averages over a period of years</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robert Hirsch, Laura DeCicco.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
