<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Annual Hydrograph Timing • EGRET</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Annual Hydrograph Timing">
<meta property="og:description" content="EGRET">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-53797708-7"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-53797708-7');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">EGRET</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.0.4.9001</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/Overview.html">Overview and Updates</a>
</li>
<li>
  <a href="../articles/EGRET.html">Introduction</a>
</li>
<li>
  <a href="../reference/index.html">Function Help Pages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Enhancements.html">Enhancements</a>
    </li>
    <li>
      <a href="../articles/WRTDSK.html">WRTDS Kalman</a>
    </li>
    <li>
      <a href="../articles/parallel.html">Running in Parallel</a>
    </li>
    <li>
      <a href="../articles/rResid.html">Random Residuals</a>
    </li>
    <li>
      <a href="../articles/SeasonalFraction.html">Seasonal Analysis</a>
    </li>
    <li>
      <a href="../articles/streamflow_trend.html">Daily Streamflow Trends</a>
    </li>
    <li>
      <a href="../articles/TrendsByMonth.html">Trends by month</a>
    </li>
    <li>
      <a href="../articles/AlternativeQMethod.html">Alternative Q Method</a>
    </li>
    <li>
      <a href="../articles/Annual_Hydrograph_Timing.html">Annual_Hydrograph_Timing</a>
    </li>
  </ul>
</li>
<li>
  <a href="../articles/References_WRTDS.html">Bibliograpy</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/USGS-R/EGRET">
    <span class="fas fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="Annual_Hydrograph_Timing_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Annual Hydrograph Timing</h1>
                        <h4 class="author">Robert M. Hirsch</h4>
            
            <h4 class="date">3/16/2021</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/USGS-R/EGRET/blob/master/vignettes/Annual_Hydrograph_Timing.Rmd"><code>vignettes/Annual_Hydrograph_Timing.Rmd</code></a></small>
      <div class="hidden name"><code>Annual_Hydrograph_Timing.Rmd</code></div>

    </div>

    
    
<p>A common question in the analysis of the impacts of climate change on hydrology is about shifts in the timing of the annual hydrograph. This is particularly of interest in areas dominated by snowmelt. The new function in EGRET designed to do the necessary data analysis for this is cumQDate. This function identifies the date, in each year, when a specified fraction of the runoff from the watershed has flowed past the streamgage. The analysis can be set up to consider a portion of the year, or the whole year starting in January. A typical version of this analysis would be to consider a snowmelt period that is defined (by the user) as the months of March through June. The function can be set up to determine the first day on which more than half of the total March through June runoff has passed the streamgage. Here is an example for the Merced River near Happy Isles Bridge, Yosemite National Park, California.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://pubs.usgs.gov/tm/04/a10/">EGRET</a></span><span class="op">)</span>
<span class="va">sta</span> <span class="op">&lt;-</span> <span class="st">"11264500"</span>
<span class="va">INFO</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/INFOdataframe.html">readNWISInfo</a></span><span class="op">(</span><span class="va">sta</span>, <span class="st">"00060"</span>, interactive <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">Daily</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/readNWISDaily.html">readNWISDaily</a></span><span class="op">(</span><span class="va">sta</span>, <span class="st">"00060"</span>, <span class="st">"1916-01-01"</span>, <span class="st">"2020-12-31"</span><span class="op">)</span></code></pre></div>
<pre><code>## There are 38352 data points, and 38352 days.</code></pre>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">eList</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/as.egret.html">as.egret</a></span><span class="op">(</span><span class="va">INFO</span>, <span class="va">Daily</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">Daily</span><span class="op">)</span></code></pre></div>
<pre><code>##       Date                  Q                 Julian          Month       
##  Min.   :1916-01-01   Min.   :  0.04248   Min.   :24105   Min.   : 1.000  
##  1st Qu.:1942-04-01   1st Qu.:  0.84951   1st Qu.:33693   1st Qu.: 4.000  
##  Median :1968-07-01   Median :  2.86000   Median :43281   Median : 7.000  
##  Mean   :1968-07-01   Mean   : 10.06120   Mean   :43281   Mean   : 6.523  
##  3rd Qu.:1994-10-01   3rd Qu.: 10.70377   3rd Qu.:52868   3rd Qu.:10.000  
##  Max.   :2020-12-31   Max.   :255.70112   Max.   :62456   Max.   :12.000  
##                                                                           
##       Day           DecYear        MonthSeq      waterYear   
##  Min.   :  1.0   Min.   :1916   Min.   : 793   Min.   :1916  
##  1st Qu.: 93.0   1st Qu.:1942   1st Qu.:1108   1st Qu.:1942  
##  Median :184.0   Median :1968   Median :1423   Median :1968  
##  Mean   :183.8   Mean   :1968   Mean   :1423   Mean   :1968  
##  3rd Qu.:275.0   3rd Qu.:1995   3rd Qu.:1738   3rd Qu.:1995  
##  Max.   :366.0   Max.   :2021   Max.   :2052   Max.   :2021  
##                                                              
##   Qualifier               i              LogQ               Q7           
##  Length:38352       Min.   :    1   Min.   :-3.1588   Min.   :  0.05299  
##  Class :character   1st Qu.: 9589   1st Qu.:-0.1631   1st Qu.:  0.88591  
##  Mode  :character   Median :19177   Median : 1.0508   Median :  2.93282  
##                     Mean   :19177   Mean   : 1.0896   Mean   : 10.06269  
##                     3rd Qu.:28764   3rd Qu.: 2.3706   3rd Qu.: 11.09919  
##                     Max.   :38352   Max.   : 5.5440   Max.   :118.00034  
##                                                       NA's   :6          
##       Q30           
##  Min.   :  0.06135  
##  1st Qu.:  1.02224  
##  Median :  3.17687  
##  Mean   : 10.06804  
##  3rd Qu.: 12.27818  
##  Max.   :100.38322  
##  NA's   :29</code></pre>
<p>To call cumQDate we need to specify a fraction of the year for this analysis. In this first case we will use the entire calendar year and the fraction of the runoff we are interested in is half of the annual total.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">annualSeriesCal</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cumQdate.html">cumQdate</a></span><span class="op">(</span><span class="va">eList</span>, paStart <span class="op">=</span> <span class="fl">1</span>, paLong <span class="op">=</span> <span class="fl">12</span>, fract <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span>
<span class="co"># let's look at the first 5 rows of the results:</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">annualSeriesCal</span><span class="op">)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,] 1916  152
## [2,] 1917  162
## [3,] 1918  162
## [4,] 1919  139
## [5,] 1920  150
## [6,] 1921  151</code></pre>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># and let's plot it</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">annualSeriesCal</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, <span class="va">annualSeriesCal</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, xlab <span class="op">=</span> <span class="st">"Year"</span>, ylab <span class="op">=</span> <span class="st">"Day of the Year"</span>, main <span class="op">=</span> <span class="st">"Day of the year for half the annual runoff\nMerced River at Happy Isles"</span><span class="op">)</span></code></pre></div>
<p><img src="Annual_Hydrograph_Timing_files/figure-html/unnamed-chunk-2-1.png" width="700"></p>
<p>We can do it again with a different designation of the time span. This time we will only look at the part of the year from April 1 through July 31. In addition, we will fit a loess model to the results and plot that.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">annualSeriesMelt</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cumQdate.html">cumQdate</a></span><span class="op">(</span><span class="va">eList</span>, paStart <span class="op">=</span> <span class="fl">4</span>, paLong <span class="op">=</span> <span class="fl">4</span>, fract <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span>
<span class="va">annualSeriesMelt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">annualSeriesMelt</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">annualSeriesMelt</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Year"</span>, <span class="st">"Day"</span><span class="op">)</span>
<span class="va">loessMod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/loess.html">loess</a></span><span class="op">(</span><span class="va">Day</span> <span class="op">~</span> <span class="va">Year</span>, data <span class="op">=</span> <span class="va">annualSeriesMelt</span>, span <span class="op">=</span> <span class="fl">0.9</span>, control <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/loess.control.html">loess.control</a></span><span class="op">(</span>surface <span class="op">=</span> <span class="st">"direct"</span><span class="op">)</span><span class="op">)</span>
<span class="va">predDay</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">loessMod</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Year <span class="op">=</span> <span class="va">annualSeriesMelt</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span>, se <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">annualSeriesMelt</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, <span class="va">annualSeriesMelt</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, xlab <span class="op">=</span> <span class="st">"Year"</span>, ylab <span class="op">=</span> <span class="st">"Day of the Year"</span>, main <span class="op">=</span> <span class="st">"Day of the year for half the annual runoff for April through July\nMerced River at Happy Isles"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">annualSeriesMelt</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, <span class="va">predDay</span><span class="op">$</span><span class="va">fit</span>, type <span class="op">=</span> <span class="st">"l"</span>, col <span class="op">=</span> <span class="st">"red"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p><img src="Annual_Hydrograph_Timing_files/figure-html/unnamed-chunk-3-1.png" width="700"></p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># what follows is just a list of the values along the loess curve</span>
<span class="va">predDay</span><span class="op">$</span><span class="va">fit</span></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
## 148.3251 148.2981 148.2764 148.2599 148.2483 148.2413 148.2386 148.2400 
##        9       10       11       12       13       14       15       16 
## 148.2453 148.2541 148.2661 148.2812 148.2993 148.3201 148.3434 148.3693 
##       17       18       19       20       21       22       23       24 
## 148.3974 148.4279 148.4605 148.4952 148.5320 148.5709 148.6117 148.6547 
##       25       26       27       28       29       30       31       32 
## 148.6998 148.7470 148.7966 148.8486 148.9032 148.9606 149.0209 149.0844 
##       33       34       35       36       37       38       39       40 
## 149.1512 149.2216 149.2960 149.3749 149.4585 149.5475 149.6422 149.7430 
##       41       42       43       44       45       46       47       48 
## 149.8501 149.9632 150.0812 150.2014 150.3182 150.4220 150.4994 150.4932 
##       49       50       51       52       53       54       55       56 
## 150.4685 150.4268 150.3687 150.2960 150.2125 150.1227 150.0298 149.9352 
##       57       58       59       60       61       62       63       64 
## 149.8384 149.7395 149.6375 149.5309 149.4284 149.3284 149.2292 149.1290 
##       65       66       67       68       69       70       71       72 
## 149.0265 148.9208 148.8110 148.6967 148.5774 148.4529 148.3229 148.1873 
##       73       74       75       76       77       78       79       80 
## 148.0460 147.8992 147.7469 147.5894 147.4268 147.2593 147.0872 146.9106 
##       81       82       83       84       85       86       87       88 
## 146.7297 146.5446 146.3555 146.1625 145.9655 145.7646 145.5599 145.3514 
##       89       90       91       92       93       94       95       96 
## 145.1392 144.9232 144.7036 144.4804 144.2535 144.0231 143.7891 143.5517 
##       97       98       99      100      101      102      103      104 
## 143.3107 143.0662 142.8180 142.5662 142.3109 142.0520 141.7895 141.5235 
##      105 
## 141.2539</code></pre>
<p>What this graph tells us is that from 1916 to the early 1960’s the day when half of the April - July runoff happened around day 150 (which is May 31). Since the early 1960’s it has been declining such that in 2020 the middle of the runoff is around day 141, which is May 22. So the timing of the half-runoff period has moved up about 9 days from the early 1960’s to the present.</p>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robert Hirsch, Laura DeCicco.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
