<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Making WRTDS_K flux estimates • EGRET</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Making WRTDS_K flux estimates">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-53797708-7"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-53797708-7');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">EGRET</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.0.3.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/EGRET.html">Introduction</a>
</li>
<li>
  <a href="../reference/index.html">Function Help Pages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Enhancements.html">Enhancements</a>
    </li>
    <li>
      <a href="../articles/Making%20WRTDS_K%20flux%20estimates.html">WRTDS-K</a>
    </li>
    <li>
      <a href="../articles/parallel.html">Running in Parallel</a>
    </li>
    <li>
      <a href="../articles/rResid.html">Random Residuals</a>
    </li>
    <li>
      <a href="../articles/SeasonalFraction.html">Seasonal Analysis</a>
    </li>
    <li>
      <a href="../articles/streamflow_trend.html">Daily Streamflow Trends</a>
    </li>
    <li>
      <a href="../articles/TrendsByMonth.Rmd">Trends by month</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Bibliograpy
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/References_WRTDS.html">WRTDS</a>
    </li>
    <li>
      <a href="../articles/References_Extend.html">Extending Methods</a>
    </li>
    <li>
      <a href="../articles/References_Region.html">Regional Studies</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/USGS-R/EGRET">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Making WRTDS_K flux estimates</h1>
                        <h4 class="author">Robert M. Hirsch</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/USGS-R/EGRET/blob/master/vignettes/Making%20WRTDS_K%20flux%20estimates.Rmd"><code>vignettes/Making WRTDS_K flux estimates.Rmd</code></a></small>
      <div class="hidden name"><code>Making WRTDS_K flux estimates.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This document provides a basic set of instructions for calculating WRTDS_K estimates of both concentration and flux (or “load”). It will not give the background or motivation for WRTDS_K. There are now two published papers that lay out the motivation for using this approach, describe the mathematics, and show the results compared to other methods. Those two publications can be found at: <a href="https://pubs.er.usgs.gov/publication/sir20195084" class="uri">https://pubs.er.usgs.gov/publication/sir20195084</a> and <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025338" class="uri">https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025338</a> .</p>
<p>The most important thing to know is that these are intended for use for providing the best possible estimates of the actual fluxes on each day, or month, or season, or year in the record. They are not intended for use in evaluating trends (which we would do using flow-normalized flux).</p>
</div>
<div id="what-one-needs-in-order-to-run-this-are-the-following-items" class="section level2">
<h2 class="hasAnchor">
<a href="#what-one-needs-in-order-to-run-this-are-the-following-items" class="anchor"></a>What one needs, in order to run this are the following items:</h2>
<ul>
<li><p>A data set which must already be in the form of an EGRET workspace containing an eList that has all four components of an <strong>eList (INFO, Daily, Sample, surfaces)</strong>. That is, it must be the data and a WRTDS model based on that data that is already estimated. The data set must be in the form of an “.RData” file that contains an <strong>eList</strong>, Nothing else needs to be in that file but if there is other stuff, that’s ok. The discussion and example shown here is carried out on a data set that contains no censored data (“less than values”) and it never has more than one observation on a given day. The description of the method and the examples run in the two papers mentioned are this kind of data set. In the last section of this vignette there will be an explanation of how the method has been generalized to handle these two special cases. The software presented here is able to properly handle data sets that have either or both of these properties (censoring and multiple observations per day).</p></li>
<li><p>There is a set of code (which you will see just below here). You need to copy that block of code into the working directory you will be using. You can give it the name “functionsForK.R” although any name will be ok. When you are ready to run an analysis you will need to source that code. It contains several functions.</p></li>
<li><p>There are four R packages required: <strong>EGRET, lubridate, dplyr, and MASS</strong>. Make sure all of them are loaded on your computer from CRAN.</p></li>
</ul>
<p>Now here is the code.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">################ you can call this functionsForK.R</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="co"># functionsForK is a set of add-ons to EGRET</span></a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="co"># for doing the WRTDS_K estimation</span></a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="co"># All fuctions (except for one) written by</span></a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="co"># Robert M. Hirsch, in 2019</span></a>
<a class="sourceLine" id="cb1-6" data-line-number="6"><span class="co"># this file is December 17, 2019</span></a>
<a class="sourceLine" id="cb1-7" data-line-number="7">#############################</a>
<a class="sourceLine" id="cb1-8" data-line-number="8"><span class="co"># makeDailyK</span></a>
<a class="sourceLine" id="cb1-9" data-line-number="9"><span class="co">#  This function takes an existing eList </span></a>
<a class="sourceLine" id="cb1-10" data-line-number="10"><span class="co">#  Including the estimated model (the surfaces object in the eList)</span></a>
<a class="sourceLine" id="cb1-11" data-line-number="11"><span class="co">#  And produces the daily WRTDS_K estimates of concentration and flux</span></a>
<a class="sourceLine" id="cb1-12" data-line-number="12"><span class="co"># it requires MASS, EGRET, lubridate, and dplyr</span></a>
<a class="sourceLine" id="cb1-13" data-line-number="13">###############################</a>
<a class="sourceLine" id="cb1-14" data-line-number="14">makeDailyK &lt;-<span class="st"> </span><span class="cf">function</span>(eList, <span class="dt">rho =</span> <span class="fl">0.90</span>, <span class="dt">niter =</span> <span class="dv">200</span>, <span class="dt">seed =</span> <span class="dv">376168</span>){</a>
<a class="sourceLine" id="cb1-15" data-line-number="15">  <span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(seed)</a>
<a class="sourceLine" id="cb1-16" data-line-number="16">  <span class="co"># this part is to set up the array of runs of missing values</span></a>
<a class="sourceLine" id="cb1-17" data-line-number="17">  localEList &lt;-<span class="st"> </span><span class="kw">cleanUp</span>(eList)</a>
<a class="sourceLine" id="cb1-18" data-line-number="18">  localDaily &lt;-<span class="st"> </span><span class="kw">populateDailySamp</span>(localEList<span class="op">$</span>Daily, localEList<span class="op">$</span>Sample)</a>
<a class="sourceLine" id="cb1-19" data-line-number="19">  numDays &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(localDaily<span class="op">$</span>Date)</a>
<a class="sourceLine" id="cb1-20" data-line-number="20">  numDaysP &lt;-<span class="st"> </span>numDays <span class="op">+</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-21" data-line-number="21">  <span class="co"># set up DailyGen which will hold the daily generated flux values for all days and all iterations</span></a>
<a class="sourceLine" id="cb1-22" data-line-number="22">  DailyGen &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="dv">0</span>, numDays <span class="op">*</span><span class="st"> </span>niter)</a>
<a class="sourceLine" id="cb1-23" data-line-number="23">  <span class="kw"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(DailyGen) &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(numDays, niter)</a>
<a class="sourceLine" id="cb1-24" data-line-number="24">  <span class="co">#   x is a vector of the standardized residuals for each day</span></a>
<a class="sourceLine" id="cb1-25" data-line-number="25">  <span class="co">#   most of the elements of x will be NA but those from sampled days will have values</span></a>
<a class="sourceLine" id="cb1-26" data-line-number="26">  x &lt;-<span class="st"> </span>localDaily<span class="op">$</span>stdResid</a>
<a class="sourceLine" id="cb1-27" data-line-number="27">  <span class="co">#    xP is x that has been padded with a 0 at the start and a 0 at the end</span></a>
<a class="sourceLine" id="cb1-28" data-line-number="28">  <span class="co">#    thus it is a vector that always starts and ends with non-missing values</span></a>
<a class="sourceLine" id="cb1-29" data-line-number="29">  xP &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,x,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb1-30" data-line-number="30">  zz &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rle.html">rle</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(xP))</a>
<a class="sourceLine" id="cb1-31" data-line-number="31">  <span class="co">#    zz$lengths is a vector of run lengths</span></a>
<a class="sourceLine" id="cb1-32" data-line-number="32">  <span class="co">#    zz$values is a vector of the values: TRUE means it is a run of missings, </span></a>
<a class="sourceLine" id="cb1-33" data-line-number="33">  <span class="co">#       FALSE means it is a run of non-missing values</span></a>
<a class="sourceLine" id="cb1-34" data-line-number="34">  nRuns &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(zz<span class="op">$</span>lengths)</a>
<a class="sourceLine" id="cb1-35" data-line-number="35">  zends &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span>(zz<span class="op">$</span>lengths)</a>
<a class="sourceLine" id="cb1-36" data-line-number="36">  nRunsM &lt;-<span class="st"> </span>nRuns <span class="op">-</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-37" data-line-number="37">  zstarts &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,zends[<span class="dv">1</span><span class="op">:</span>nRunsM])</a>
<a class="sourceLine" id="cb1-38" data-line-number="38">  <span class="co"># doGap is the indexs of the runs that are missing values (it is just the even integers)</span></a>
<a class="sourceLine" id="cb1-39" data-line-number="39">  doGap &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="dv">2</span>,nRunsM,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb1-40" data-line-number="40">  <span class="co"># numGap is the number of groups of missing values to be filled in</span></a>
<a class="sourceLine" id="cb1-41" data-line-number="41">  numGap &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(doGap)</a>
<a class="sourceLine" id="cb1-42" data-line-number="42">  <span class="co"># now we are ready to do the iterations to generate the series</span></a>
<a class="sourceLine" id="cb1-43" data-line-number="43">  <span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>niter){</a>
<a class="sourceLine" id="cb1-44" data-line-number="44">    localEList &lt;-<span class="st"> </span><span class="kw">cleanUp</span>(eList)</a>
<a class="sourceLine" id="cb1-45" data-line-number="45">    <span class="co"># this next step adds a trueConc column to Daily, and it is NA if there is no sample value</span></a>
<a class="sourceLine" id="cb1-46" data-line-number="46">    <span class="co"># it also adds the stdResid column to Daily</span></a>
<a class="sourceLine" id="cb1-47" data-line-number="47">    localDaily &lt;-<span class="st"> </span><span class="kw">populateDailySamp</span>(localEList<span class="op">$</span>Daily, localEList<span class="op">$</span>Sample)</a>
<a class="sourceLine" id="cb1-48" data-line-number="48">    x &lt;-<span class="st"> </span>localDaily<span class="op">$</span>stdResid</a>
<a class="sourceLine" id="cb1-49" data-line-number="49">    <span class="co">#    xxP is x that has been padded with a 0 at the start and a 0 at the end</span></a>
<a class="sourceLine" id="cb1-50" data-line-number="50">    <span class="co">#    thus it is a vector that always starts and ends with non-missing values</span></a>
<a class="sourceLine" id="cb1-51" data-line-number="51">    xxP &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,x,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb1-52" data-line-number="52">    <span class="co"># now we are going to loop through all the gaps that need to be filled in</span></a>
<a class="sourceLine" id="cb1-53" data-line-number="53">    <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>numGap) {</a>
<a class="sourceLine" id="cb1-54" data-line-number="54">      iGap&lt;-doGap[i]</a>
<a class="sourceLine" id="cb1-55" data-line-number="55">      startFill&lt;-zstarts[iGap]</a>
<a class="sourceLine" id="cb1-56" data-line-number="56">      endFill&lt;-zends[iGap]<span class="op">+</span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-57" data-line-number="57">      nFill&lt;-zz<span class="op">$</span>length[iGap]<span class="op">+</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb1-58" data-line-number="58">      xfill&lt;-<span class="kw">genmissing</span>(xxP[startFill],xxP[endFill],rho,nFill)</a>
<a class="sourceLine" id="cb1-59" data-line-number="59">      xxP[startFill<span class="op">:</span>endFill]&lt;-xfill}</a>
<a class="sourceLine" id="cb1-60" data-line-number="60">    <span class="co"># now we need to strip out the padded days</span></a>
<a class="sourceLine" id="cb1-61" data-line-number="61">    xResid &lt;-<span class="st"> </span>xxP[<span class="dv">2</span><span class="op">:</span>numDaysP]</a>
<a class="sourceLine" id="cb1-62" data-line-number="62">    xConc &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Log.html">exp</a></span>((xResid<span class="op">*</span>localDaily<span class="op">$</span>SE)<span class="op">+</span>localDaily<span class="op">$</span>yHat)</a>
<a class="sourceLine" id="cb1-63" data-line-number="63">    DailyGen[,iter] &lt;-<span class="st"> </span>xConc <span class="op">*</span><span class="st"> </span>localDaily<span class="op">$</span>Q <span class="op">*</span><span class="st"> </span><span class="fl">86.4</span></a>
<a class="sourceLine" id="cb1-64" data-line-number="64">  }</a>
<a class="sourceLine" id="cb1-65" data-line-number="65">  <span class="co"># now we take means over all the iterations</span></a>
<a class="sourceLine" id="cb1-66" data-line-number="66">  GenMean &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numDays)</a>
<a class="sourceLine" id="cb1-67" data-line-number="67">  Daily &lt;-<span class="st"> </span>eList<span class="op">$</span>Daily</a>
<a class="sourceLine" id="cb1-68" data-line-number="68">  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="op">:</span><span class="st"> </span>numDays) {GenMean[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DailyGen[i,])}</a>
<a class="sourceLine" id="cb1-69" data-line-number="69">  Daily<span class="op">$</span>GenFlux &lt;-<span class="st"> </span>GenMean</a>
<a class="sourceLine" id="cb1-70" data-line-number="70">  Daily<span class="op">$</span>GenConc &lt;-<span class="st"> </span>Daily<span class="op">$</span>GenFlux <span class="op">/</span><span class="st"> </span>(Daily<span class="op">$</span>Q <span class="op">*</span><span class="st"> </span><span class="fl">86.4</span>)</a>
<a class="sourceLine" id="cb1-71" data-line-number="71">  <span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(Daily, <span class="st">"niter"</span>) &lt;-<span class="st"> </span>niter</a>
<a class="sourceLine" id="cb1-72" data-line-number="72">  <span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(Daily, <span class="st">"rho"</span>) &lt;-<span class="st"> </span>rho</a>
<a class="sourceLine" id="cb1-73" data-line-number="73">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(Daily)</a>
<a class="sourceLine" id="cb1-74" data-line-number="74">}</a>
<a class="sourceLine" id="cb1-75" data-line-number="75"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-76" data-line-number="76"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-77" data-line-number="77"></a>
<a class="sourceLine" id="cb1-78" data-line-number="78">genmissing&lt;-<span class="cf">function</span>(X1,XN,rho,N){</a>
<a class="sourceLine" id="cb1-79" data-line-number="79">  <span class="co"># this code was done by Tim Cohn</span></a>
<a class="sourceLine" id="cb1-80" data-line-number="80">  <span class="co">#  X1 is the value before the gap</span></a>
<a class="sourceLine" id="cb1-81" data-line-number="81">  <span class="co">#  XN is the value after the gap</span></a>
<a class="sourceLine" id="cb1-82" data-line-number="82">  <span class="co">#  rho is the lag one autocorrelation</span></a>
<a class="sourceLine" id="cb1-83" data-line-number="83">  <span class="co">#  N is the length of the sequence including X1 and XN </span></a>
<a class="sourceLine" id="cb1-84" data-line-number="84">  <span class="co">#     it is two more than the gap length</span></a>
<a class="sourceLine" id="cb1-85" data-line-number="85">  <span class="co">#   it requires the MASS package</span></a>
<a class="sourceLine" id="cb1-86" data-line-number="86">  C&lt;-<span class="kw"><a href="https://rdrr.io/r/base/t.html">t</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/chol.html">chol</a></span>(rho<span class="op">^</span><span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/outer.html">outer</a></span>(<span class="dv">1</span><span class="op">:</span>N,<span class="dv">1</span><span class="op">:</span>N, <span class="st">"-"</span>))[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>,N,<span class="dv">2</span><span class="op">:</span>(N<span class="dv">-1</span>)),<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>,N,<span class="dv">2</span><span class="op">:</span>(N<span class="dv">-1</span>))]))</a>
<a class="sourceLine" id="cb1-87" data-line-number="87">  (C<span class="op">%*%</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw">ginv</span>(C[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])<span class="op">%*%</span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(X1,XN),<span class="kw"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(N<span class="dv">-2</span>)))[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>,<span class="dv">3</span><span class="op">:</span>N,<span class="dv">2</span>)]</a>
<a class="sourceLine" id="cb1-88" data-line-number="88">}</a>
<a class="sourceLine" id="cb1-89" data-line-number="89"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-90" data-line-number="90"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-91" data-line-number="91"></a>
<a class="sourceLine" id="cb1-92" data-line-number="92">####################################</a>
<a class="sourceLine" id="cb1-93" data-line-number="93"><span class="co"># This function cleans up a Sample data frame</span></a>
<a class="sourceLine" id="cb1-94" data-line-number="94"><span class="co"># It randomly picks one sample out of the multiple samples on a given day</span></a>
<a class="sourceLine" id="cb1-95" data-line-number="95"><span class="co"># and it makes an augmented record substituting a random value on</span></a>
<a class="sourceLine" id="cb1-96" data-line-number="96"><span class="co"># those days with censored data</span></a>
<a class="sourceLine" id="cb1-97" data-line-number="97"><span class="co">#  Note, it must have an eList with a valid surfaces matrix </span></a>
<a class="sourceLine" id="cb1-98" data-line-number="98"><span class="co"># and the Sample data frame in the eList needs to have yHat and SE already calculated</span></a>
<a class="sourceLine" id="cb1-99" data-line-number="99">####################################</a>
<a class="sourceLine" id="cb1-100" data-line-number="100">cleanUp &lt;-<span class="st"> </span><span class="cf">function</span>(eList){</a>
<a class="sourceLine" id="cb1-101" data-line-number="101">  Sample &lt;-<span class="st"> </span><span class="kw">random_subset</span>(eList<span class="op">$</span>Sample, Julian)</a>
<a class="sourceLine" id="cb1-102" data-line-number="102">  eListClean &lt;-<span class="st"> </span><span class="kw"><a href="../reference/as.egret.html">as.egret</a></span>(eList<span class="op">$</span>INFO, eList<span class="op">$</span>Daily, Sample, eList<span class="op">$</span>surfaces)</a>
<a class="sourceLine" id="cb1-103" data-line-number="103">  eListClean &lt;-<span class="st"> </span><span class="kw"><a href="../reference/makeAugmentedSample.html">makeAugmentedSample</a></span>(eListClean)</a>
<a class="sourceLine" id="cb1-104" data-line-number="104">  Sample &lt;-<span class="st"> </span>eListClean<span class="op">$</span>Sample</a>
<a class="sourceLine" id="cb1-105" data-line-number="105">  Sample<span class="op">$</span>Uncen &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-106" data-line-number="106">  Sample<span class="op">$</span>ConcLow &lt;-<span class="st"> </span>Sample<span class="op">$</span>rObserved</a>
<a class="sourceLine" id="cb1-107" data-line-number="107">  Sample<span class="op">$</span>ConcHigh &lt;-<span class="st"> </span>Sample<span class="op">$</span>rObserved</a>
<a class="sourceLine" id="cb1-108" data-line-number="108">  Sample<span class="op">$</span>ConcAve &lt;-<span class="st"> </span>Sample<span class="op">$</span>rObserved</a>
<a class="sourceLine" id="cb1-109" data-line-number="109">  eListClean &lt;-<span class="st"> </span><span class="kw"><a href="../reference/as.egret.html">as.egret</a></span>(eList<span class="op">$</span>INFO, eList<span class="op">$</span>Daily, Sample, eList<span class="op">$</span>surfaces)</a>
<a class="sourceLine" id="cb1-110" data-line-number="110">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(eListClean)</a>
<a class="sourceLine" id="cb1-111" data-line-number="111">}</a>
<a class="sourceLine" id="cb1-112" data-line-number="112"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-113" data-line-number="113"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-114" data-line-number="114">####################################</a>
<a class="sourceLine" id="cb1-115" data-line-number="115"><span class="co"># function written by Laura De Cicco October 2019</span></a>
<a class="sourceLine" id="cb1-116" data-line-number="116"><span class="co">#  requires library(dplyr)</span></a>
<a class="sourceLine" id="cb1-117" data-line-number="117"><span class="co"># makes a copy of a data frame but when there are</span></a>
<a class="sourceLine" id="cb1-118" data-line-number="118"><span class="co"># multiple values with the specified col_name it randomly</span></a>
<a class="sourceLine" id="cb1-119" data-line-number="119"><span class="co"># picks one of them and drops the others</span></a>
<a class="sourceLine" id="cb1-120" data-line-number="120"><span class="co"># useage newSample &lt;- random_subset(Sample, Julian)</span></a>
<a class="sourceLine" id="cb1-121" data-line-number="121">###################################</a>
<a class="sourceLine" id="cb1-122" data-line-number="122">random_subset &lt;-<span class="st"> </span><span class="cf">function</span>(df, col_name){</a>
<a class="sourceLine" id="cb1-123" data-line-number="123">  </a>
<a class="sourceLine" id="cb1-124" data-line-number="124">  df_dups &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-125" data-line-number="125"><span class="st">    </span><span class="kw">group_by</span>({{col_name}}) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-126" data-line-number="126"><span class="st">    </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(<span class="kw">n</span>() <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-127" data-line-number="127"><span class="st">    </span><span class="kw">group_by</span>({{col_name}}) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-128" data-line-number="128"><span class="st">    </span><span class="kw">sample_n</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-129" data-line-number="129">  </a>
<a class="sourceLine" id="cb1-130" data-line-number="130">  subDF &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-131" data-line-number="131"><span class="st">    </span><span class="kw">group_by</span>({{col_name}}) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-132" data-line-number="132"><span class="st">    </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(<span class="kw">n</span>() <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-133" data-line-number="133"><span class="st">    </span><span class="kw">bind_rows</span>(df_dups) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-134" data-line-number="134"><span class="st">    </span><span class="kw">arrange</span>({{col_name}})</a>
<a class="sourceLine" id="cb1-135" data-line-number="135">  </a>
<a class="sourceLine" id="cb1-136" data-line-number="136">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(subDF)</a>
<a class="sourceLine" id="cb1-137" data-line-number="137">}</a>
<a class="sourceLine" id="cb1-138" data-line-number="138"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-139" data-line-number="139"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-140" data-line-number="140">###########################</a>
<a class="sourceLine" id="cb1-141" data-line-number="141">populateDailySamp&lt;-<span class="cf">function</span>(<span class="dt">localDaily=</span>Daily,<span class="dt">localSample=</span>Sample) {</a>
<a class="sourceLine" id="cb1-142" data-line-number="142">  numDays&lt;-<span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(localDaily<span class="op">$</span>Julian)</a>
<a class="sourceLine" id="cb1-143" data-line-number="143">  numSamp&lt;-<span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(localSample<span class="op">$</span>Julian)</a>
<a class="sourceLine" id="cb1-144" data-line-number="144">  trueConc &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>,numDays)</a>
<a class="sourceLine" id="cb1-145" data-line-number="145">  trueFlux &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numDays)</a>
<a class="sourceLine" id="cb1-146" data-line-number="146">  stdResid &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>,numDays)</a>
<a class="sourceLine" id="cb1-147" data-line-number="147">  DailyOffset&lt;-localDaily<span class="op">$</span>Julian[<span class="dv">1</span>]<span class="op">-</span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-148" data-line-number="148">  <span class="cf">for</span>(samp <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>numSamp){iday&lt;-localSample<span class="op">$</span>Julian[samp]<span class="op">-</span>DailyOffset</a>
<a class="sourceLine" id="cb1-149" data-line-number="149">  trueConc[iday]&lt;-localSample<span class="op">$</span>ConcAve[samp]</a>
<a class="sourceLine" id="cb1-150" data-line-number="150">  trueFlux[iday] &lt;-<span class="st"> </span>trueConc[iday] <span class="op">*</span><span class="st"> </span>localDaily<span class="op">$</span>Q[iday] <span class="op">*</span><span class="st"> </span><span class="fl">86.4</span></a>
<a class="sourceLine" id="cb1-151" data-line-number="151">  stdResid[iday]&lt;-(<span class="kw"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(trueConc[iday])<span class="op">-</span>localDaily<span class="op">$</span>yHat[iday])<span class="op">/</span>localDaily<span class="op">$</span>SE[iday]</a>
<a class="sourceLine" id="cb1-152" data-line-number="152">  }</a>
<a class="sourceLine" id="cb1-153" data-line-number="153">  retDaily&lt;-<span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(localDaily,trueConc,trueFlux, stdResid)</a>
<a class="sourceLine" id="cb1-154" data-line-number="154">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(retDaily)</a>
<a class="sourceLine" id="cb1-155" data-line-number="155">}</a>
<a class="sourceLine" id="cb1-156" data-line-number="156"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-157" data-line-number="157">setupYearsKalmanFlux &lt;-<span class="st"> </span><span class="cf">function</span> (localDaily, <span class="dt">paLong =</span> <span class="dv">12</span>, <span class="dt">paStart =</span> <span class="dv">10</span>) </a>
<a class="sourceLine" id="cb1-158" data-line-number="158">{</a>
<a class="sourceLine" id="cb1-159" data-line-number="159"><span class="co"># note that fluxes returned are the sum of the daily fluxes</span></a>
<a class="sourceLine" id="cb1-160" data-line-number="160"><span class="co"># the units on the fluxes are all metric tons </span></a>
<a class="sourceLine" id="cb1-161" data-line-number="161">  numDays &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(localDaily<span class="op">$</span>MonthSeq)</a>
<a class="sourceLine" id="cb1-162" data-line-number="162">  firstMonthSeq &lt;-<span class="st"> </span>localDaily<span class="op">$</span>MonthSeq[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb1-163" data-line-number="163">  lastMonthSeq &lt;-<span class="st"> </span>localDaily<span class="op">$</span>MonthSeq[numDays]</a>
<a class="sourceLine" id="cb1-164" data-line-number="164">  Starts &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(paStart, lastMonthSeq, <span class="dv">12</span>)</a>
<a class="sourceLine" id="cb1-165" data-line-number="165">  Ends &lt;-<span class="st"> </span>Starts <span class="op">+</span><span class="st"> </span>paLong <span class="op">-</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-166" data-line-number="166">  StartEndSeq &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(Starts, Ends)</a>
<a class="sourceLine" id="cb1-167" data-line-number="167">  StartEndSeq &lt;-<span class="st"> </span>StartEndSeq[(StartEndSeq<span class="op">$</span>Starts <span class="op">&gt;=</span><span class="st"> </span>firstMonthSeq) <span class="op">&amp;</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-168" data-line-number="168"><span class="st">                               </span>(StartEndSeq<span class="op">$</span>Ends <span class="op">&lt;=</span><span class="st"> </span>lastMonthSeq), ]</a>
<a class="sourceLine" id="cb1-169" data-line-number="169">  firstMonth &lt;-<span class="st"> </span>StartEndSeq[<span class="dv">1</span>, <span class="dv">1</span>]</a>
<a class="sourceLine" id="cb1-170" data-line-number="170">  numYears &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(StartEndSeq<span class="op">$</span>Starts)</a>
<a class="sourceLine" id="cb1-171" data-line-number="171">  DecYear &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-172" data-line-number="172">  Q &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-173" data-line-number="173">  ConcDay &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-174" data-line-number="174">  GenConc &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-175" data-line-number="175">  FluxDay &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-176" data-line-number="176">  GenFlux &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="ot">NA</span>, numYears)</a>
<a class="sourceLine" id="cb1-177" data-line-number="177">  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>numYears) {</a>
<a class="sourceLine" id="cb1-178" data-line-number="178">    startMonth &lt;-<span class="st"> </span>(i <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span><span class="dv">12</span> <span class="op">+</span><span class="st"> </span>firstMonth</a>
<a class="sourceLine" id="cb1-179" data-line-number="179">    stopMonth &lt;-<span class="st"> </span>startMonth <span class="op">+</span><span class="st"> </span>paLong <span class="op">-</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb1-180" data-line-number="180">    DailyYear &lt;-<span class="st"> </span>localDaily[<span class="kw"><a href="https://rdrr.io/r/base/which.html">which</a></span>(localDaily<span class="op">$</span>MonthSeq <span class="op">%in%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-181" data-line-number="181"><span class="st">                                    </span>startMonth<span class="op">:</span>stopMonth), ]</a>
<a class="sourceLine" id="cb1-182" data-line-number="182">    counter &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(DailyYear<span class="op">$</span>FluxDay), <span class="dv">0</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-183" data-line-number="183">    <span class="cf">if</span> (<span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(counter) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) {</a>
<a class="sourceLine" id="cb1-184" data-line-number="184">      good &lt;-<span class="st"> </span>(<span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(counter) <span class="op">==</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(counter))</a>
<a class="sourceLine" id="cb1-185" data-line-number="185">    }</a>
<a class="sourceLine" id="cb1-186" data-line-number="186">    <span class="cf">else</span> {</a>
<a class="sourceLine" id="cb1-187" data-line-number="187">      good &lt;-<span class="st"> </span><span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb1-188" data-line-number="188">    }</a>
<a class="sourceLine" id="cb1-189" data-line-number="189">    DecYear[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DailyYear<span class="op">$</span>DecYear)</a>
<a class="sourceLine" id="cb1-190" data-line-number="190">    Q[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DailyYear<span class="op">$</span>Q)</a>
<a class="sourceLine" id="cb1-191" data-line-number="191">    <span class="cf">if</span> (good) {</a>
<a class="sourceLine" id="cb1-192" data-line-number="192">      ConcDay[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DailyYear<span class="op">$</span>ConcDay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-193" data-line-number="193">      GenConc[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(DailyYear<span class="op">$</span>GenConc, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-194" data-line-number="194">      FluxDay[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(DailyYear<span class="op">$</span>FluxDay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">/</span><span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb1-195" data-line-number="195">      GenFlux[i] &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(DailyYear<span class="op">$</span>GenFlux, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">/</span><span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb1-196" data-line-number="196">    }</a>
<a class="sourceLine" id="cb1-197" data-line-number="197">  }</a>
<a class="sourceLine" id="cb1-198" data-line-number="198">  AnnualResults &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(DecYear, Q, ConcDay, GenConc, FluxDay, GenFlux)</a>
<a class="sourceLine" id="cb1-199" data-line-number="199">  <span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(AnnualResults,<span class="st">"paStart"</span>) &lt;-<span class="st"> </span>paStart</a>
<a class="sourceLine" id="cb1-200" data-line-number="200">  <span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(AnnualResults,<span class="st">"paLong"</span>) &lt;-<span class="st"> </span>paLong</a>
<a class="sourceLine" id="cb1-201" data-line-number="201">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(AnnualResults)</a>
<a class="sourceLine" id="cb1-202" data-line-number="202">}</a>
<a class="sourceLine" id="cb1-203" data-line-number="203"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-204" data-line-number="204"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-205" data-line-number="205"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-206" data-line-number="206">computeAnnual &lt;-<span class="st"> </span><span class="cf">function</span>(eList, Daily, <span class="dt">paStart =</span> <span class="dv">10</span>, <span class="dt">paLong =</span> <span class="dv">12</span>) {</a>
<a class="sourceLine" id="cb1-207" data-line-number="207">  <span class="co"># it provides a printed list of the annual values and a set of plots</span></a>
<a class="sourceLine" id="cb1-208" data-line-number="208">  <span class="co"># if you don't want that output </span></a>
<a class="sourceLine" id="cb1-209" data-line-number="209">  <span class="co"># you can get the same thing with AnnualResults &lt;- setupYearsKalmanFlux()</span></a>
<a class="sourceLine" id="cb1-210" data-line-number="210">  <span class="co"># This function creates an annual series of results</span></a>
<a class="sourceLine" id="cb1-211" data-line-number="211">  <span class="co"># The annual results can be for a specific season, specified by paStart and paLong</span></a>
<a class="sourceLine" id="cb1-212" data-line-number="212">  <span class="co"># The default is the water year</span></a>
<a class="sourceLine" id="cb1-213" data-line-number="213">  <span class="co"># FluxDay is the traditional regression estimate of Flux</span></a>
<a class="sourceLine" id="cb1-214" data-line-number="214">  <span class="co"># GenFlux is the Kalman Filter estimate</span></a>
<a class="sourceLine" id="cb1-215" data-line-number="215">  <span class="co"># ConcDay is the traditional regression estimate of Concentration </span></a>
<a class="sourceLine" id="cb1-216" data-line-number="216">  <span class="co"># GenConc is the Kalman Filter estimate</span></a>
<a class="sourceLine" id="cb1-217" data-line-number="217">  AnnualResults &lt;-<span class="st"> </span><span class="kw">setupYearsKalmanFlux</span>(Daily, <span class="dt">paStart =</span> paStart, <span class="dt">paLong =</span> paLong)</a>
<a class="sourceLine" id="cb1-218" data-line-number="218">  <span class="co"># in the print out Q is the annual mean value in m^3/s</span></a>
<a class="sourceLine" id="cb1-219" data-line-number="219">  <span class="co"># the two flux values are in metric tons kilograms (1000 kg)</span></a>
<a class="sourceLine" id="cb1-220" data-line-number="220">  <span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(eList<span class="op">$</span>INFO<span class="op">$</span>shortName)</a>
<a class="sourceLine" id="cb1-221" data-line-number="221">  <span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(eList<span class="op">$</span>INFO<span class="op">$</span>paramShortName)</a>
<a class="sourceLine" id="cb1-222" data-line-number="222">  period &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(<span class="st">"paStart is"</span>,paStart,<span class="st">" paLong is"</span>,paLong, <span class="dt">sep =</span> <span class="st">" "</span>)</a>
<a class="sourceLine" id="cb1-223" data-line-number="223">  <span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(period)</a>
<a class="sourceLine" id="cb1-224" data-line-number="224">  <span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(AnnualResults)</a>
<a class="sourceLine" id="cb1-225" data-line-number="225">  yMax &lt;-<span class="st"> </span><span class="fl">1.1</span> <span class="op">*</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(AnnualResults<span class="op">$</span>FluxDay, AnnualResults<span class="op">$</span>GenFlux)</a>
<a class="sourceLine" id="cb1-226" data-line-number="226">  nYears &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(AnnualResults[,<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb1-227" data-line-number="227">  <span class="co"># first a plot of just the WRTDS estimate</span></a>
<a class="sourceLine" id="cb1-228" data-line-number="228">  xMin &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Round.html">floor</a></span>(AnnualResults[<span class="dv">1</span>,<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb1-229" data-line-number="229">  xMax &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Round.html">ceiling</a></span>(AnnualResults[nYears,<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb1-230" data-line-number="230">  xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(xMin,xMax)</a>
<a class="sourceLine" id="cb1-231" data-line-number="231">  title1 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(eList<span class="op">$</span>INFO<span class="op">$</span>shortName,eList<span class="op">$</span>INFO<span class="op">$</span>paramShortName,</a>
<a class="sourceLine" id="cb1-232" data-line-number="232">                  <span class="st">"</span><span class="ch">\n</span><span class="st">Annual Flux Estimates: WRTDS in red, WRTDS-K in green</span><span class="ch">\n</span><span class="st">"</span>,period,<span class="dt">sep=</span><span class="st">"  "</span>)</a>
<a class="sourceLine" id="cb1-233" data-line-number="233">  title2 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(eList<span class="op">$</span>INFO<span class="op">$</span>shortName,eList<span class="op">$</span>INFO<span class="op">$</span>paramShortName,</a>
<a class="sourceLine" id="cb1-234" data-line-number="234">                  <span class="st">"</span><span class="ch">\n</span><span class="st">Comparison of the two flux estimates</span><span class="ch">\n</span><span class="st">"</span>,period,<span class="dt">sep=</span><span class="st">"  "</span>)</a>
<a class="sourceLine" id="cb1-235" data-line-number="235">  <span class="co">#</span></a>
<a class="sourceLine" id="cb1-236" data-line-number="236">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(AnnualResults<span class="op">$</span>DecYear, AnnualResults<span class="op">$</span>FluxDay, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">cex =</span> <span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">xaxs =</span> <span class="st">"i"</span>,</a>
<a class="sourceLine" id="cb1-237" data-line-number="237">       <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>, yMax), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">ylab =</span> <span class="st">"Annual flux, metric tons"</span>, </a>
<a class="sourceLine" id="cb1-238" data-line-number="238">       <span class="dt">main =</span> title1, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">col =</span> <span class="st">"red"</span>,</a>
<a class="sourceLine" id="cb1-239" data-line-number="239">       <span class="dt">tck =</span> <span class="fl">0.02</span>, <span class="dt">cex.main =</span> <span class="fl">1.1</span>, <span class="dt">cex.lab =</span> <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb1-240" data-line-number="240">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">new =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-241" data-line-number="241">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(AnnualResults<span class="op">$</span>DecYear, AnnualResults<span class="op">$</span>GenFlux, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">col =</span> <span class="st">"green"</span>, <span class="dt">xlim =</span> xlim, <span class="dt">xaxs =</span> <span class="st">"i"</span>,</a>
<a class="sourceLine" id="cb1-242" data-line-number="242">       <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>, yMax), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">ylab =</span> <span class="st">""</span>, <span class="dt">main =</span> <span class="st">""</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">tck =</span> <span class="fl">0.02</span>, <span class="dt">axes =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb1-243" data-line-number="243">  <span class="co"># scatter plot</span></a>
<a class="sourceLine" id="cb1-244" data-line-number="244">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(AnnualResults<span class="op">$</span>FluxDay, AnnualResults<span class="op">$</span>GenFlux, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">cex =</span> <span class="fl">1.3</span>, <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>, yMax), <span class="dt">xaxs =</span> <span class="st">"i"</span>,</a>
<a class="sourceLine" id="cb1-245" data-line-number="245">       <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>, yMax), <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">"WRTDS estimate of annual flux, in metric tons"</span>, <span class="dt">ylab =</span> </a>
<a class="sourceLine" id="cb1-246" data-line-number="246">         <span class="st">"WRTDS_K estimate of annual flux, in metric tons"</span>, <span class="dt">cex.main =</span> <span class="fl">1.1</span>, <span class="dt">cex.lab =</span> <span class="fl">0.95</span>, <span class="dt">cex.axis =</span> <span class="fl">1.2</span>, </a>
<a class="sourceLine" id="cb1-247" data-line-number="247">       <span class="dt">main =</span> title2)</a>
<a class="sourceLine" id="cb1-248" data-line-number="248">  <span class="kw"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="dt">a =</span> <span class="dv">0</span>, <span class="dt">b =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-249" data-line-number="249">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(AnnualResults)</a>
<a class="sourceLine" id="cb1-250" data-line-number="250">}</a>
<a class="sourceLine" id="cb1-251" data-line-number="251"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-252" data-line-number="252"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-253" data-line-number="253"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-254" data-line-number="254">plotTimeSlice &lt;-<span class="st"> </span><span class="cf">function</span>(eList, Daily, start, end){</a>
<a class="sourceLine" id="cb1-255" data-line-number="255">  Daily &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/subset.html">subset</a></span>(Daily,DecYear <span class="op">&gt;=</span><span class="st"> </span>start <span class="op">&amp;</span><span class="st"> </span>DecYear <span class="op">&lt;=</span><span class="st"> </span>end)</a>
<a class="sourceLine" id="cb1-256" data-line-number="256">  concHigh &lt;-<span class="st"> </span><span class="fl">1.1</span> <span class="op">*</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(Daily<span class="op">$</span>trueConc,Daily<span class="op">$</span>GenConc,Daily<span class="op">$</span>ConcDay,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-257" data-line-number="257">  concLow &lt;-<span class="st"> </span><span class="fl">0.9</span> <span class="op">*</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span>(Daily<span class="op">$</span>trueConc,Daily<span class="op">$</span>GenConc,Daily<span class="op">$</span>ConcDay,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-258" data-line-number="258">  fluxHigh &lt;-<span class="st"> </span><span class="fl">1.1</span> <span class="op">*</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(Daily<span class="op">$</span>trueFlux,Daily<span class="op">$</span>GenFlux,Daily<span class="op">$</span>FluxDay,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-259" data-line-number="259">  fluxLow &lt;-<span class="st"> </span><span class="fl">0.9</span> <span class="op">*</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span>(Daily<span class="op">$</span>trueFlux,Daily<span class="op">$</span>GenFlux,Daily<span class="op">$</span>FluxDay,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-260" data-line-number="260">  <span class="co"># figure out which data symbol to use, red for uncensored, brown for censored</span></a>
<a class="sourceLine" id="cb1-261" data-line-number="261">  eList<span class="op">$</span>Sample<span class="op">$</span>color &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span>(eList<span class="op">$</span>Sample<span class="op">$</span>Uncen <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">"red"</span>, <span class="st">"cyan4"</span>)</a>
<a class="sourceLine" id="cb1-262" data-line-number="262">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">tck =</span> <span class="fl">0.02</span>, <span class="dt">las =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-263" data-line-number="263">  <span class="co"># first concentration, then flux</span></a>
<a class="sourceLine" id="cb1-264" data-line-number="264">  name &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(eList<span class="op">$</span>INFO<span class="op">$</span>shortName, eList<span class="op">$</span>INFO<span class="op">$</span>paramShortName, <span class="dt">sep =</span> <span class="st">" "</span>)</a>
<a class="sourceLine" id="cb1-265" data-line-number="265">  ratio &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(Daily<span class="op">$</span>GenConc) <span class="op">/</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(Daily<span class="op">$</span>ConcDay)</a>
<a class="sourceLine" id="cb1-266" data-line-number="266">  fratio &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/format.html">format</a></span>(ratio, <span class="dt">digits =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb1-267" data-line-number="267">  concTitle &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(name,<span class="st">"</span><span class="ch">\n</span><span class="st">Concentrations, Black is WRTDS, Green is WRTDS_K</span><span class="ch">\n</span><span class="st">Data in red, (rl in blue if &lt;), Ratio of means is"</span>, fratio, <span class="dt">sep =</span> <span class="st">" "</span>)</a>
<a class="sourceLine" id="cb1-268" data-line-number="268">  </a>
<a class="sourceLine" id="cb1-269" data-line-number="269">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(Daily<span class="op">$</span>DecYear, Daily<span class="op">$</span>ConcDay, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), </a>
<a class="sourceLine" id="cb1-270" data-line-number="270">       <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(concLow,concHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">cex.main =</span> <span class="fl">0.9</span>, </a>
<a class="sourceLine" id="cb1-271" data-line-number="271">       <span class="dt">ylab =</span> <span class="st">"Concentration, in milligrams per Liter"</span>,</a>
<a class="sourceLine" id="cb1-272" data-line-number="272">       <span class="dt">main =</span> concTitle)</a>
<a class="sourceLine" id="cb1-273" data-line-number="273">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">new =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-274" data-line-number="274">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(eList<span class="op">$</span>Sample<span class="op">$</span>DecYear, eList<span class="op">$</span>Sample<span class="op">$</span>ConcHigh, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">cex =</span> <span class="fl">1.1</span>, <span class="dt">col =</span> eList<span class="op">$</span>Sample<span class="op">$</span>color, </a>
<a class="sourceLine" id="cb1-275" data-line-number="275">       <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(concLow,concHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>,</a>
<a class="sourceLine" id="cb1-276" data-line-number="276">       <span class="dt">ylab =</span> <span class="st">""</span>, <span class="dt">main =</span> <span class="st">""</span>, <span class="dt">axes =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb1-277" data-line-number="277">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">new =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-278" data-line-number="278">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(Daily<span class="op">$</span>DecYear, Daily<span class="op">$</span>GenConc, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), </a>
<a class="sourceLine" id="cb1-279" data-line-number="279">       <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(concLow,concHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">col =</span> <span class="st">"green"</span>, </a>
<a class="sourceLine" id="cb1-280" data-line-number="280">       <span class="dt">ylab =</span> <span class="st">""</span>, <span class="dt">main =</span> <span class="st">""</span>, <span class="dt">axes =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb1-281" data-line-number="281">  <span class="co"># flux graph</span></a>
<a class="sourceLine" id="cb1-282" data-line-number="282">  ratio &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(Daily<span class="op">$</span>GenFlux) <span class="op">/</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/mean.html">mean</a></span>(Daily<span class="op">$</span>FluxDay)</a>
<a class="sourceLine" id="cb1-283" data-line-number="283">  fratio &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/format.html">format</a></span>(ratio, <span class="dt">digits =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb1-284" data-line-number="284">  fluxTitle &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(name,<span class="st">"</span><span class="ch">\n</span><span class="st">Flux, Black is WRTDS, Green is WRTDS_K</span><span class="ch">\n</span><span class="st">Data in red, (rl in blue if &lt;), Ratio of means is"</span>, fratio, <span class="dt">sep =</span> <span class="st">" "</span>)</a>
<a class="sourceLine" id="cb1-285" data-line-number="285">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(Daily<span class="op">$</span>DecYear, Daily<span class="op">$</span>FluxDay, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), </a>
<a class="sourceLine" id="cb1-286" data-line-number="286">       <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(fluxLow,fluxHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">las =</span> <span class="dv">1</span>,  </a>
<a class="sourceLine" id="cb1-287" data-line-number="287">       <span class="dt">ylab =</span> <span class="st">"Flux, in kg per day"</span>, <span class="dt">cex.main =</span> <span class="fl">0.95</span>,</a>
<a class="sourceLine" id="cb1-288" data-line-number="288">       <span class="dt">main =</span> fluxTitle)</a>
<a class="sourceLine" id="cb1-289" data-line-number="289">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">new =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-290" data-line-number="290">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(eList<span class="op">$</span>Sample<span class="op">$</span>DecYear, eList<span class="op">$</span>Sample<span class="op">$</span>ConcHigh <span class="op">*</span><span class="st"> </span>eList<span class="op">$</span>Sample<span class="op">$</span>Q <span class="op">*</span><span class="st"> </span><span class="fl">86.4</span>, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">pch =</span> <span class="dv">20</span>, </a>
<a class="sourceLine" id="cb1-291" data-line-number="291">       <span class="dt">cex =</span> <span class="fl">1.1</span>, <span class="dt">col =</span> eList<span class="op">$</span>Sample<span class="op">$</span>color, </a>
<a class="sourceLine" id="cb1-292" data-line-number="292">       <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(fluxLow,fluxHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>,</a>
<a class="sourceLine" id="cb1-293" data-line-number="293">       <span class="dt">ylab =</span> <span class="st">""</span>, <span class="dt">main =</span> <span class="st">""</span>, <span class="dt">axes =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb1-294" data-line-number="294">  <span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">new =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-295" data-line-number="295">  <span class="kw"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(Daily<span class="op">$</span>DecYear, Daily<span class="op">$</span>GenFlux, <span class="dt">log =</span> <span class="st">"y"</span>, <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(start, end), </a>
<a class="sourceLine" id="cb1-296" data-line-number="296">       <span class="dt">xaxs =</span> <span class="st">"i"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(fluxLow,fluxHigh), <span class="dt">yaxs =</span> <span class="st">"i"</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">col =</span> <span class="st">"green"</span>, </a>
<a class="sourceLine" id="cb1-297" data-line-number="297">       <span class="dt">ylab =</span> <span class="st">""</span>, <span class="dt">main =</span> <span class="st">""</span>, <span class="dt">axes =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb1-298" data-line-number="298">}</a>
<a class="sourceLine" id="cb1-299" data-line-number="299"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-300" data-line-number="300"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-301" data-line-number="301"><span class="co">#</span></a>
<a class="sourceLine" id="cb1-302" data-line-number="302"><span class="co"># script for identifying if a Sample data frame has</span></a>
<a class="sourceLine" id="cb1-303" data-line-number="303"><span class="co"># any days with multiple samples</span></a>
<a class="sourceLine" id="cb1-304" data-line-number="304"><span class="co"># or any samples that are uncensored</span></a>
<a class="sourceLine" id="cb1-305" data-line-number="305">specialCase &lt;-<span class="st"> </span><span class="cf">function</span>(eList) {</a>
<a class="sourceLine" id="cb1-306" data-line-number="306">  Sample &lt;-<span class="st"> </span>eList<span class="op">$</span>Sample</a>
<a class="sourceLine" id="cb1-307" data-line-number="307">  n &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(Sample<span class="op">$</span>Date)</a>
<a class="sourceLine" id="cb1-308" data-line-number="308">  days &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/unique.html">unique</a></span>(Sample<span class="op">$</span>Julian)</a>
<a class="sourceLine" id="cb1-309" data-line-number="309">  nDays &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(days)</a>
<a class="sourceLine" id="cb1-310" data-line-number="310">  mult &lt;-<span class="st"> </span><span class="cf">if</span>(n <span class="op">&gt;</span><span class="st"> </span>nDays) <span class="ot">TRUE</span> <span class="cf">else</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb1-311" data-line-number="311">  nUncen &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(Sample<span class="op">$</span>Uncen)</a>
<a class="sourceLine" id="cb1-312" data-line-number="312">  cen &lt;-<span class="st"> </span><span class="cf">if</span>(nUncen <span class="op">&lt;</span><span class="st"> </span>n) <span class="ot">TRUE</span> <span class="cf">else</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb1-313" data-line-number="313">  <span class="co"># when mult is TRUE, needs to go through the subsampling process each time</span></a>
<a class="sourceLine" id="cb1-314" data-line-number="314">  <span class="co"># when cen is TRUE it needs to go through the random augmentation </span></a>
<a class="sourceLine" id="cb1-315" data-line-number="315">  special &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(mult, cen)</a>
<a class="sourceLine" id="cb1-316" data-line-number="316">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(special)</a>
<a class="sourceLine" id="cb1-317" data-line-number="317">}</a></code></pre></div>
</div>
<div id="running-the-software" class="section level2">
<h2 class="hasAnchor">
<a href="#running-the-software" class="anchor"></a>Running the software</h2>
<p>Make sure that the <strong>.RData</strong> file and the code are in the workspace you want to work in and that you have properly set the working directory with the <strong>setwd()</strong> command. Be sure that the eList contains the <strong>surfaces</strong> matrix, which is the estimated WRTDS model, based on the data set in the <strong>Sample</strong> data frame. Here is an example of a run, with some comments along the way. The actual commands are shown in the shaded part.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(EGRET)</a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(MASS)</a>
<a class="sourceLine" id="cb2-3" data-line-number="3"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(lubridate)</a></code></pre></div>
<pre><code>## 
## Attaching package: 'lubridate'</code></pre>
<pre><code>## The following object is masked from 'package:base':
## 
##     date</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(dplyr)</a></code></pre></div>
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:lubridate':
## 
##     intersect, setdiff, union</code></pre>
<pre><code>## The following object is masked from 'package:MASS':
## 
##     select</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/load.html">load</a></span>(<span class="st">"rockCr.tp.RData"</span>) <span class="co"># the name of your EGRET workspace</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span>(<span class="st">"functionsForK.R"</span>)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="co"># now we will run the WRTDS_K estimation (I'm using the defaults for now)</span></a>
<a class="sourceLine" id="cb11-4" data-line-number="4">DailyK &lt;-<span class="st"> </span><span class="kw">makeDailyK</span>(eList)</a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(DailyK))</a></code></pre></div>
<pre><code>##       Date                  Q                 Julian          Month       
##  Min.   :2006-01-01   Min.   : 0.001699   Min.   :56978   Min.   : 1.000  
##  1st Qu.:2009-03-09   1st Qu.: 0.024352   1st Qu.:58142   1st Qu.: 3.000  
##  Median :2012-05-16   Median : 0.053094   Median :59306   Median : 6.000  
##  Mean   :2012-05-16   Mean   : 0.177447   Mean   :59306   Mean   : 6.435  
##  3rd Qu.:2015-07-24   3rd Qu.: 0.129974   3rd Qu.:60469   3rd Qu.: 9.000  
##  Max.   :2018-09-30   Max.   :16.140602   Max.   :61633   Max.   :12.000  
##                                                                           
##       Day           DecYear        MonthSeq      waterYear   
##  Min.   :  1.0   Min.   :2006   Min.   :1873   Min.   :2006  
##  1st Qu.: 91.0   1st Qu.:2009   1st Qu.:1911   1st Qu.:2009  
##  Median :180.0   Median :2012   Median :1949   Median :2012  
##  Mean   :181.1   Mean   :2012   Mean   :1949   Mean   :2012  
##  3rd Qu.:270.0   3rd Qu.:2016   3rd Qu.:1987   3rd Qu.:2015  
##  Max.   :366.0   Max.   :2019   Max.   :2025   Max.   :2018  
##                                                              
##   Qualifier               i             LogQ              Q7          
##  Length:4656        Min.   :   1   Min.   :-6.378   Min.   :0.003681  
##  Class :character   1st Qu.:1165   1st Qu.:-3.715   1st Qu.:0.034031  
##  Mode  :character   Median :2328   Median :-2.936   Median :0.076759  
##                     Mean   :2328   Mean   :-2.806   Mean   :0.177639  
##                     3rd Qu.:3492   3rd Qu.:-2.040   3rd Qu.:0.178184  
##                     Max.   :4656   Max.   : 2.781   Max.   :3.300126  
##                                                     NA's   :6         
##       Q30                yHat              SE            ConcDay       
##  Min.   :0.007145   Min.   :-2.848   Min.   :0.2977   Min.   :0.06238  
##  1st Qu.:0.049918   1st Qu.:-2.143   1st Qu.:0.3661   1st Qu.:0.12879  
##  Median :0.111814   Median :-1.817   Median :0.4203   Median :0.17797  
##  Mean   :0.178359   Mean   :-1.733   Mean   :0.4572   Mean   :0.26460  
##  3rd Qu.:0.234119   3rd Qu.:-1.468   3rd Qu.:0.5320   3rd Qu.:0.26421  
##  Max.   :1.354904   Max.   : 1.358   Max.   :0.7834   Max.   :5.39851  
##  NA's   :29                                                            
##     FluxDay             FNConc            FNFlux            GenFlux        
##  Min.   :   0.014   Min.   :0.09381   Min.   :  0.4727   Min.   :   0.014  
##  1st Qu.:   0.282   1st Qu.:0.16312   1st Qu.:  1.3266   1st Qu.:   0.284  
##  Median :   0.704   Median :0.23973   Median :  4.0625   Median :   0.681  
##  Mean   :  19.701   Mean   :0.26303   Mean   : 19.3821   Mean   :  17.837  
##  3rd Qu.:   2.699   3rd Qu.:0.33200   3rd Qu.: 14.4545   3rd Qu.:   2.373  
##  Max.   :6929.255   Max.   :0.81444   Max.   :545.3019   Max.   :6936.258  
##                                                                            
##     GenConc      
##  Min.   :0.0500  
##  1st Qu.:0.1217  
##  Median :0.1715  
##  Mean   :0.2482  
##  3rd Qu.:0.2417  
##  Max.   :6.9288  
## </code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(DailyK,<span class="st">"niter"</span>))</a></code></pre></div>
<pre><code>## [1] 200</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(DailyK,<span class="st">"rho"</span>))</a></code></pre></div>
<pre><code>## [1] 0.9</code></pre>
<p>The object being created here is a data frame called <strong>DailyK</strong>. It looks just like <strong>Daily</strong> but with some columns added. What are the extra columns?</p>
<p><strong>trueConc</strong> is the measured concentration on the days when there is a value, many will be NA</p>
<p><strong>trueFlux</strong> (in kg/day) flux for the days when concentration is measured</p>
<p><strong>stdResid</strong> (dimensionless) this is the standardized residual from the WRTDS model estimate, for the days when concentration is measured. It is (ln(trueConc) - yHat) / SE.</p>
<p><strong>yHat</strong> is the WRTDS estimate of the natural log of concentration and SE is the standard error of the WRTDS model for the specific time, discharge, and season.</p>
<p><strong>GenFlux</strong> is the WRTDS_K estimate of the flux for each day (in kg/day) <strong>GenConc</strong> is the WRTDS_K estimate of the concentration for each day (in kg/day)</p>
</div>
<div id="summarizing-results-at-an-annual-time-step" class="section level1">
<h1 class="hasAnchor">
<a href="#summarizing-results-at-an-annual-time-step" class="anchor"></a>Summarizing results at an annual time step</h1>
<p>Now we can take the results from the <strong>DailyK</strong> data frame and compute annual flux values. We will do that for the regular WRTDS and for WRTDS_K (using the data in two columns of <strong>DailyK</strong> the <strong>FluxDay</strong> column and the <strong>GenFlux</strong> column). We can also do these computations for some period of analysis other than the water year, but for now, we will just show the water year computations. The function used is called <strong>computeAnnual</strong> and it produces a data frame called <strong>AnnualResults</strong> and also produces some graphics that show the two types of results. Notice that <strong>AnnualResults</strong> has some attributes that go with it that will tell you what the period of analysis was. They are printed here. Note that the function <strong>computeAnnual</strong> actually does more than the computations, it prints out the content of AnnualResults and it also makes two graphs that tell you some things about how the two types of estimates compare to each other.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">AnnualResults &lt;-<span class="st"> </span><span class="kw">computeAnnual</span>(eList, <span class="dt">Daily =</span> DailyK)</a></code></pre></div>
<pre><code>## [1] "Rock Creek at Kentucky Road in Independence, MO"
## [1] "Phosphorus"
## [1] "paStart is 10  paLong is 12"
##     DecYear          Q   ConcDay   GenConc   FluxDay   GenFlux
## 1  2007.247 0.17898031 0.2962950 0.3035116 10.503918 11.412228
## 2  2008.248 0.27055586 0.3516980 0.3027088 16.375702 14.377783
## 3  2009.247 0.26025897 0.3759310 0.3822140  9.550358  9.926332
## 4  2010.247 0.27538327 0.3747984 0.3130897  8.891109  7.960983
## 5  2011.247 0.14896523 0.2471670 0.2414275  5.124139  4.921882
## 6  2012.248 0.08488400 0.1868972 0.1980234  1.476794  1.548080
## 7  2013.247 0.13601784 0.2226408 0.1978812  3.398696  2.656734
## 8  2014.247 0.10545581 0.1980464 0.1976627  3.090438  3.171315
## 9  2015.247 0.20777738 0.2707080 0.2217504  8.453969  6.268860
## 10 2016.248 0.25410346 0.2935102 0.2302717  8.170745  5.707152
## 11 2017.247 0.19541107 0.2342773 0.2421715 12.077357 10.410761
## 12 2018.247 0.09552708 0.1734324 0.1714012  3.436251  3.403874</code></pre>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-3-1.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-3-2.png" width="700"></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(AnnualResults, <span class="st">"paStart"</span>))</a></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(AnnualResults, <span class="st">"paLong"</span>))</a></code></pre></div>
<pre><code>## [1] 12</code></pre>
<p>The content of <strong>AnnualResults</strong> is fairly obvious.</p>
<p><strong>DecYear</strong> is the mean day of the year for the period of analysis, for example, water year 2007 would have a mean day of 2007.247 (end of March of 2007).</p>
<p><strong>Q</strong> is the mean discharge in m^3/s.</p>
<p><strong>ConcDay</strong> is the mean value of concentration for the year from the regular WRTDS model, in mg/L.</p>
<p><strong>GenConc</strong> is the mean value of concentration for the year from the WRTDS_K model, in mg/L.</p>
<p><strong>FluxDay</strong> is the sum of the daily flux values from the regular WRTDS model, in units of metric tons (same as 10^3 kg).</p>
<p><strong>GenFlux</strong> is the sum of the daily flux values from the WRTDS_K model, in units of metric tons (same as 10^3 kg).</p>
<p>The first graph compares the time series of the two flux records: WRTDS in red and WRTDS_K in green. This graph is fairly typical of what we have seen in a number of studies so far. There are a number of years in which the two estimates are practically identical (e.g. 2011, 2012, 2014) but there are a few cases where they diverge significantly. In this example, in those cases the WRTDS_K estimate is substantially lower than the WRTDS estimate. What that means is that the tendency for WRTDS to predict values that are too high has been reduced. It happens that the flux bias statistic for this data set is 0.35, suggesting that the model has a tendency to estimate fluxes that are too high.</p>
<p>The second graph is just another way to look at these same results, but as a scatter plot of results from the two methods. What we see is a tendency for a fair number of years to plot close to the 1:1 line but four of them are substantially below the line (meaning their WRTDS_K estimates are lower than their WRTDS estimates).</p>
<p>Seeing this, we’d like to dig in a bit and see what’s going on.</p>
</div>
<div id="looking-at-parts-of-the-record-to-see-how-wrtds-and-wrtds_k-are-working" class="section level1">
<h1 class="hasAnchor">
<a href="#looking-at-parts-of-the-record-to-see-how-wrtds-and-wrtds_k-are-working" class="anchor"></a>Looking at parts of the record to see how WRTDS and WRTDS_K are working</h1>
<p>We have a function that produces graphics that show, as a time series, the daily true values (for the days that have samples), the WRTDS estimates for every day, and the WRTDS_K estimates for every day. We could plot the whole record, but the ups and downs of the curves would be so tight that we really couldn’t see what’s going on. So, we let the user pick a time slice to look at. It produces two plots, the first is for concentration (it is typically easier to see what is happening in the estimation with the concentration graphs) and the second is for flux (discharge plays such a big role here that the propagation of error from the concentrations gets somewhat obscured, but flux is, after all, what we are interested in here).</p>
<p>We will look at two examples here, in each case looking at about a half a year. The first one (2018) is a year in which there was very good agreement between the estimates, and the second one (2015) is a year with a large difference between the methods. Let’s see what those results look like.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">plotTimeSlice</span>(eList, <span class="dt">Daily =</span> DailyK, <span class="dt">start =</span> <span class="fl">2018.2</span>, <span class="dt">end =</span> <span class="fl">2018.7</span>)</a></code></pre></div>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-4-1.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-4-2.png" width="700"></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">plotTimeSlice</span>(eList, <span class="dt">Daily =</span> DailyK, <span class="dt">start =</span> <span class="fl">2015.2</span>, <span class="dt">end =</span> <span class="fl">2015.7</span>)</a></code></pre></div>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-4-3.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-4-4.png" width="700"></p>
<p>What can we learn from these figures? The first, which is a half year in 2018. Note before we start that all of these graphs show either concentration or flux on a log scale. We will start with the concentration graph. We see that there are 7 observed values. When we compare the observed values (red dots) with the WRTDS estimates (black line) for each of those days we see two negative residuals followed by a positive residual a negative a positive and the final two have residuals that are close to zero. Once we get past the second observation (around 2018.25) we see the WRTDS_K curve (in green) going back a forth from being a little above the WRTDS curve to a little below. This alternation indicates that the errors of the model are not ones that persist for very many days and thus the corrections based on these errors don’t persist for very many days. One other thing to note is that the model suggests a big spike in concentration around 2018.4 but there are no samples very close in time to this event (there is a gap of about a month) and the big discharge event took place about half way between these two sample dates. Given this lack of information close to the date of the large flow event, the WRTDS_K will not result in much of a change during this event as compared to what we estimate from WRTDS. The upshot of all of this is that the residuals information doesn’t make much difference during this half year in WRTDS_K results and we really don’t change our estimate by much.</p>
<p>Now, contrast this with the 2015 results. Here we see the first residual being very near zero, but after that every one of them is substantially negative (below the black line). What this is telling us is that something was going on in this part of 2015 such that concentrations were always lower than the WRTDS model (based on the years around 2015, both before and after). We don’t happen to know why this departure exists (perhaps it relates to what tributaries were most active or to something about antecedent conditions). What it does tell us is that generally, throughout the period 2015.35 through 2015.65 it is a good guess that concentrations are likely to have been lower than what the WRTDS model estimates they should be. The math of the WRTDS_K model ends up giving us a green curve that is always below the black curve throughout this period. That means, when the WRTDS_K estimate is summarized for the whole 2015 water year it will be a good deal lower than what WRTDS would give us. Looking at the last of the four graphs (for flux), even though the black and green curves track pretty close to each other the ratio of the two mean fluxes is 0.45. So, the persistant negative residuals causes us to make a major downward adjustment to our estimated flux for the period.</p>
<p>As a generalization we can say that WRTDS_K will result in large adjustments when two things happen: 1) there is a strong persistence of the residuals (long runs of positives or long runs of negatives), and 2) when there are samples collected on or close to the days of maximum flux and they show large absolute residuals.</p>
<p>One final note. These graphs also have an additional bit of information. They say, in their title “Ratio of means is xx”. This ratio is specific to the time slice shown in the plot (not the whole record being estimated) and the ratio stated is WRTDS_K estimate divided by the regular WRTDS estimate.</p>
</div>
<div id="two-options-available-setting-rho-and-setting-niter" class="section level1">
<h1 class="hasAnchor">
<a href="#two-options-available-setting-rho-and-setting-niter" class="anchor"></a>Two options available (setting rho and setting niter)</h1>
<p>One of the things that the user must select is the rho value. We don’t have a strong theoretical basis for selecting the right value of rho, although our research has shown that the results are not highly sensitive to it. In the paper published in Zhang and Hirsch (2019) (see the second URL near the start of this document) we do make some generalizations about the selection of rho. We found that for nitrate a slightly higher rho value (such as 0.95) may be better than for other constitutents such as TP, OrthoP, Suspended Sediment, or Chloride for which values like 0.85 or 0.9 may be better. The somewhat different behavior for nitrate is explained by the fact that at many sites there are some other factors probably related to denitrification the discharge and term does not have a great amount of explanatory power in the WRTDS model. As such, placing more reliance on the results of samples that are close in time is appropriate. One can experiment with different values of rho because it is an argument in the <strong>makeDailyK</strong> function.</p>
<p>We can re-run the analysis with rho of 0.85 and see how much difference it makes. The table shown here lists the ratio the difference in annual values divided by the original annual value (so multiplying these numbers by 100 would result in differences in percent).</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">DailyK2 &lt;-<span class="st"> </span><span class="kw">makeDailyK</span>(eList, <span class="dt">rho =</span> <span class="fl">0.85</span>)</a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(DailyK2,<span class="st">"rho"</span>))</a></code></pre></div>
<pre><code>## [1] 0.85</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(DailyK2,<span class="st">"niter"</span>))</a></code></pre></div>
<pre><code>## [1] 200</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">AnnualResults2 &lt;-<span class="st"> </span><span class="kw">computeAnnual</span>(eList, <span class="dt">Daily =</span> DailyK2)</a></code></pre></div>
<pre><code>## [1] "Rock Creek at Kentucky Road in Independence, MO"
## [1] "Phosphorus"
## [1] "paStart is 10  paLong is 12"
##     DecYear          Q   ConcDay   GenConc   FluxDay   GenFlux
## 1  2007.247 0.17898031 0.2962950 0.3047198 10.503918 11.484281
## 2  2008.248 0.27055586 0.3516980 0.3155029 16.375702 15.238110
## 3  2009.247 0.26025897 0.3759310 0.3805880  9.550358  9.948663
## 4  2010.247 0.27538327 0.3747984 0.3312658  8.891109  8.274015
## 5  2011.247 0.14896523 0.2471670 0.2415491  5.124139  4.951591
## 6  2012.248 0.08488400 0.1868972 0.1960336  1.476794  1.553370
## 7  2013.247 0.13601784 0.2226408 0.2028929  3.398696  2.789326
## 8  2014.247 0.10545581 0.1980464 0.1980895  3.090438  3.192825
## 9  2015.247 0.20777738 0.2707080 0.2330521  8.453969  6.511406
## 10 2016.248 0.25410346 0.2935102 0.2449645  8.170745  6.163219
## 11 2017.247 0.19541107 0.2342773 0.2421669 12.077357 10.879251
## 12 2018.247 0.09552708 0.1734324 0.1716476  3.436251  3.333916</code></pre>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-5-1.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-5-2.png" width="700"></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">Ratios &lt;-<span class="st"> </span>(AnnualResults2 <span class="op">-</span><span class="st"> </span>AnnualResults) <span class="op">/</span><span class="st"> </span>AnnualResults</a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(Ratios)</a></code></pre></div>
<pre><code>##    DecYear Q ConcDay       GenConc FluxDay      GenFlux
## 1        0 0       0  0.0039807650       0  0.006313677
## 2        0 0       0  0.0422655465       0  0.059837223
## 3        0 0       0 -0.0042540636       0  0.002249681
## 4        0 0       0  0.0580542534       0  0.039320859
## 5        0 0       0  0.0005039279       0  0.006035998
## 6        0 0       0 -0.0100482896       0  0.003416747
## 7        0 0       0  0.0253266865       0  0.049907775
## 8        0 0       0  0.0021594544       0  0.006782641
## 9        0 0       0  0.0509659590       0  0.038690539
## 10       0 0       0  0.0638065343       0  0.079911354
## 11       0 0       0 -0.0000189604       0  0.045000568
## 12       0 0       0  0.0014377375       0 -0.020552659</code></pre>
<p>What we see here is that the change in rho from 0.9 to 0.85 makes less than a 10% difference in any of the years.</p>
<p>Setting the number of iterations to 200 (the default) seems to be sufficient. We can set a different random number seed and see how much difference it makes in the results.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">DailyK2 &lt;-<span class="st"> </span><span class="kw">makeDailyK</span>(eList, <span class="dt">seed =</span> <span class="dv">38109695</span>)</a>
<a class="sourceLine" id="cb33-2" data-line-number="2">AnnualResults2 &lt;-<span class="st"> </span><span class="kw">computeAnnual</span>(eList, <span class="dt">Daily =</span> DailyK2)</a></code></pre></div>
<pre><code>## [1] "Rock Creek at Kentucky Road in Independence, MO"
## [1] "Phosphorus"
## [1] "paStart is 10  paLong is 12"
##     DecYear          Q   ConcDay   GenConc   FluxDay   GenFlux
## 1  2007.247 0.17898031 0.2962950 0.2980348 10.503918 11.420844
## 2  2008.248 0.27055586 0.3516980 0.2984355 16.375702 13.639404
## 3  2009.247 0.26025897 0.3759310 0.3835593  9.550358  9.856361
## 4  2010.247 0.27538327 0.3747984 0.3086841  8.891109  7.732880
## 5  2011.247 0.14896523 0.2471670 0.2434325  5.124139  5.075688
## 6  2012.248 0.08488400 0.1868972 0.1973845  1.476794  1.524699
## 7  2013.247 0.13601784 0.2226408 0.1964867  3.398696  2.680148
## 8  2014.247 0.10545581 0.1980464 0.1989881  3.090438  3.233255
## 9  2015.247 0.20777738 0.2707080 0.2202788  8.453969  6.200197
## 10 2016.248 0.25410346 0.2935102 0.2269377  8.170745  5.508252
## 11 2017.247 0.19541107 0.2342773 0.2452966 12.077357 11.080569
## 12 2018.247 0.09552708 0.1734324 0.1748340  3.436251  3.781166</code></pre>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-6-1.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-6-2.png" width="700"></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">Ratios &lt;-<span class="st"> </span>(AnnualResults2 <span class="op">-</span><span class="st"> </span>AnnualResults) <span class="op">/</span><span class="st"> </span>AnnualResults</a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(Ratios)</a></code></pre></div>
<pre><code>##    DecYear Q ConcDay      GenConc FluxDay       GenFlux
## 1        0 0       0 -0.018044719       0  0.0007550509
## 2        0 0       0 -0.014116740       0 -0.0513555957
## 3        0 0       0  0.003519725       0 -0.0070490952
## 4        0 0       0 -0.014071164       0 -0.0286525439
## 5        0 0       0  0.008304999       0  0.0312493314
## 6        0 0       0 -0.003226711       0 -0.0151033182
## 7        0 0       0 -0.007047291       0  0.0088131734
## 8        0 0       0  0.006705153       0  0.0195312846
## 9        0 0       0 -0.006636557       0 -0.0109529811
## 10       0 0       0 -0.014478648       0 -0.0348510967
## 11       0 0       0  0.012904366       0  0.0643381003
## 12       0 0       0  0.020027964       0  0.1108416945</code></pre>
<p>This table shows us that, at worst the individual annual fluxes differ by about 11% and many of them differ by less than 2% in successive runs with different seeds The annual concentrations never differ by more than about 2%. This suggests that 200 is a sufficient number of iterations to run to obtain a stable result. For final calculations for publication one might want to specify niter = 500 or niter = 1000 in the call to <strong>makeDailyK</strong>, but the idea here is not perfection, but rather to make a reasonable adjustment of the flux record to account for the serial correlation of the residuals.</p>
</div>
<div id="what-about-putting-these-results-into-the-plotconchist-or-plotfluxhist-graphs" class="section level1">
<h1 class="hasAnchor">
<a href="#what-about-putting-these-results-into-the-plotconchist-or-plotfluxhist-graphs" class="anchor"></a>What about putting these results into the <strong>plotConcHist</strong> or <strong>plotFluxHist</strong> graphs</h1>
<p>Typically when we do some type of trend study we may want to create graphic outputs showing the Flow Normalized values (connected by a line) and the estimated annual values (as dots). If you want to put the WRTDS_K values on these graphs you can use some substitute functions.</p>
<p><strong>plotConcHistK</strong> works exactly like <strong>plotConcHist</strong> but there is a new second argument, it is <strong>DailyK</strong>. So in it’s simplest form the call would be <strong>plotConcHistK(eList, DailyK)</strong>. The markings in the title have a <em>(K)</em> after the word <em>Estimates</em>.</p>
<p><strong>plotFluxHistK</strong> works exactly like <strong>plotFluxHist</strong> but there is a new second argument, it is <strong>DailyK</strong>. So in it’s simplest form the call would be <strong>plotFluxHistK(eList, DailyK)</strong>. The markings in the title have a <em>(K)</em> after the word <em>Estimates</em>.</p>
<p>Here they are being used.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">plotConcHistK</span>(eList, DailyK)</a></code></pre></div>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">plotFluxHistK</span>(eList, DailyK, <span class="dt">fluxUnit =</span> <span class="dv">8</span>)</a></code></pre></div>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-7-2.png" width="700"></p>
</div>
<div id="operationalizing-this-in-a-batch-job" class="section level1">
<h1 class="hasAnchor">
<a href="#operationalizing-this-in-a-batch-job" class="anchor"></a>Operationalizing this in a batch job</h1>
<p>The process after loading the necessary packages and the functionsForK code is this.</p>
<ul>
<li>load the workspace for a site</li>
<li>give the command <strong>DailyK &lt;- makeDailyK(eList)</strong>
</li>
<li>give the command <strong>AnnualResults &lt;- computeAnnual(eList, Daily = DailyK)</strong>
</li>
<li>then save the object <strong>AnnualResults</strong>
</li>
<li>there is an alternative to this that doesn’t print out anything or plot anything. It just <strong>AnnualResults &lt;- setupYearsKalmanFlux()</strong>
</li>
<li>the tables and graphs you will probably want can all be made from the content of Annual Results, and the meta data are all in the <strong>INFO</strong> object in the <strong>eList</strong>
</li>
<li>if the iterest is in only one season of the year then modify the call to <strong>computeAnnual</strong> by adding the <strong>paStart</strong> and <strong>paLong</strong> arguments for the season you are interested in.</li>
<li>note that <strong>AnnualResults</strong> has two attributes that tell the <strong>paStart</strong> and <strong>paLong</strong>, so you can always tell what you used as your period of analysis</li>
</ul>
</div>
<div id="how-the-code-handles-two-kinds-of-special-situations" class="section level1">
<h1 class="hasAnchor">
<a href="#how-the-code-handles-two-kinds-of-special-situations" class="anchor"></a>How the code handles two kinds of special situations</h1>
<p>The description in the two publications mentioned here accurately describes how the computations work in the situation where no days in the record have more than one observed value and where no censored data exist in the record. The following section describes how the code handles data sets that violate one or both of these constraints. You don’t really have to understand this to use the software, but for completeness we are describing how these situations are handled in the code.</p>
<div id="censored-data-less-than-values" class="section level2">
<h2 class="hasAnchor">
<a href="#censored-data-less-than-values" class="anchor"></a>Censored data (less than values)</h2>
<p>In order to fill in estimates for all the days with no samples, we must have a known value on each of the sampled days. We use this known value to compute a residual on the sampled day. These known residuals on either side of a data gap are what initialize the AR(1) process that fills in all the missing values of residuals in the gap. It would be incorrect to set these censored values with the reporting limit (<strong>ConcHigh</strong>) and also incorrect to set these censored values to half the reporting limit (this would be <strong>ConcAve</strong>). The solution is this. Since we are estimating the entire time series of residuals using Monte Carlo simulation we can also use Monte Carlo methods to create an appropriate value for the sampled day. For each replicate of the whole time series we will generate random values for each of the censored sample days. We already have a function that allows us to generate these random realizations of the censored day concentration. It is the function in EGRET called <strong>makeAugmentedSample</strong>. What it does is that on each day with a censored value it defines a truncated log normal distribution and takes a random sample from that distribution to represent the unknown true value on that day. The truncated lognormal distribution is defined by the WRTDS model for that day. It uses estimates of the conditional mean of the log concentration and the conditional standard deviation of the log concentration and assumes that the conditional distribution of the logs is normal. The distribution is not the whole normal distribution, rather it is made up of the left hand tail of the distribution. The truncation point is at the log of the reporting limit for the data value. What this means is that for the censored day, we can create a Monte Carlo sample value of the log of concentration by sampling from that truncated normal distribution (which is specific to the conditions on that day). Note here that the random observation values generated here are NOT used to estimate the WRTDS model; that is done in the usual fashion using the censored sample information.</p>
<p>So now the data generation scheme is done in two phases for each iteration: First we fill in values for each of the censored days and these, combined with the uncensored values constitute the sample data set we will work from. Then we use the AR(1) process to fill in the missing days between all the sampled days. Then when we move on to the next iteration we start all over with estimating all the censored days again and then fill the gaps, etc.</p>
<p>When we plot these data sets using <strong>plotTimeSlice</strong>, when there are censored values they plot in the blue color and they are located on the vertical scale at the reporting limit (meaning that the true value lies somewhere at or below the blue dot).</p>
</div>
<div id="multiple-observations-on-a-day" class="section level2">
<h2 class="hasAnchor">
<a href="#multiple-observations-on-a-day" class="anchor"></a>Multiple observations on a day</h2>
<p>When a day has more than one observation (i.e. more than one sample value) the approach we use here is much the same as what we used in the censored value situation. What we need in order to generate the full WRTDS_K record is a set of unique values for the sampled days. So, for any day with two or more samples we will randomly pick one of them and use it as an end point for the adjacent gap periods. Then once we pick it we generate the values between the sampled days regardless of whether the sample value used is a unique value for that day or if it is randomly selected from the multiple values observed on that day. Then on the next iteration we randomly select the values for these multiply sampled days and proceed with the AR(1) process to fill in between the sampled days. In the plot produced by plotTimeSlice all of the observations are shown as red dots. Thus if there are multiple sample values on a given day they will plot along a vertical line situated on that day.</p>
</div>
<div id="an-example-with-both-special-issues" class="section level2">
<h2 class="hasAnchor">
<a href="#an-example-with-both-special-issues" class="anchor"></a>An example with both special issues</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/rm.html">rm</a></span>(eList, DailyK)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/load.html">load</a></span>(<span class="st">"test.RData"</span>) <span class="co"># the name of your EGRET workspace</span></a>
<a class="sourceLine" id="cb39-3" data-line-number="3">DailyK &lt;-<span class="st"> </span><span class="kw">makeDailyK</span>(eList)</a>
<a class="sourceLine" id="cb39-4" data-line-number="4"><span class="kw">plotTimeSlice</span>(eList, DailyK, <span class="dt">start =</span> <span class="fl">2010.2</span>, <span class="dt">end =</span> <span class="fl">2010.4</span>)</a></code></pre></div>
<p><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-8-1.png" width="700"><img src="Making%20WRTDS_K%20flux%20estimates_files/figure-html/unnamed-chunk-8-2.png" width="700"></p>
<p>If we look at the concentration graph we see two things of interest here. Right after 2010.30 there appear to be three days with censored values with a reporting limit at 0.004 mg/L. What is interesting here is that generally the green line (WRTDS_K estimates) go right through the samples (the red dots), here they don’t. That is because in the Monte Carlo simulation to “true” samples generated are always less than the reporting limit (the blue dots) so the green line lies below these points. Also, there is a case at around 2010.38 where there are two data points (red points) that lie one directly above the other. These are two sample values from the same day. The WRTDS_K estimate (green line) goes right between these two sample values because in the Monte Carlo simulation sometimes the sample value is the lower one and sometimes it is the upper one and the result is that the estimate lies between the two.</p>
</div>
</div>
<div id="final-thoughts" class="section level1">
<h1 class="hasAnchor">
<a href="#final-thoughts" class="anchor"></a>Final thoughts</h1>
<p>In a few months we expect to better integrate these WRTDS_K computations into EGRET for a new release of EGRET, but for now (December 2019) this is the way it should be implemented. Feedback is welcome before we more fully integrate it. The citations for the two papers that introduce and experiment with WRTDS_K are as follows.</p>
<p>Lee, C.J., Hirsch, R.M., and Crawford, C.G., 2019, An evaluation of methods for computing annual water-quality loads: U.S. Geological Survey Scientific Investigations Report 2019–5084, 59 p., <a href="https://doi.org/10.3133/sir20195084" class="uri">https://doi.org/10.3133/sir20195084</a>.</p>
<p>Zhang, Q. and Hirsch, R.M., 2019. River water‐quality concentration and flux estimation can be improved by accounting for serial correlation through an autoregressive model. Water Resources Research. <a href="https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019WR025338" class="uri">https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019WR025338</a></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#what-one-needs-in-order-to-run-this-are-the-following-items">What one needs, in order to run this are the following items:</a></li>
      <li><a href="#running-the-software">Running the software</a></li>
      <li><a href="#summarizing-results-at-an-annual-time-step">Summarizing results at an annual time step</a></li>
      <li><a href="#looking-at-parts-of-the-record-to-see-how-wrtds-and-wrtds_k-are-working">Looking at parts of the record to see how WRTDS and WRTDS_K are working</a></li>
      <li><a href="#two-options-available-setting-rho-and-setting-niter">Two options available (setting rho and setting niter)</a></li>
      <li><a href="#what-about-putting-these-results-into-the-plotconchist-or-plotfluxhist-graphs">What about putting these results into the <strong>plotConcHist</strong> or <strong>plotFluxHist</strong> graphs</a></li>
      <li><a href="#operationalizing-this-in-a-batch-job">Operationalizing this in a batch job</a></li>
      <li>
<a href="#how-the-code-handles-two-kinds-of-special-situations">How the code handles two kinds of special situations</a><ul class="nav nav-pills nav-stacked">
<li><a href="#censored-data-less-than-values">Censored data (less than values)</a></li>
      <li><a href="#multiple-observations-on-a-day">Multiple observations on a day</a></li>
      <li><a href="#an-example-with-both-special-issues">An example with both special issues</a></li>
      </ul>
</li>
      <li><a href="#final-thoughts">Final thoughts</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robert Hirsch, Laura DeCicco.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
