<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WRTDS-K In Development • EGRET</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="WRTDS-K In Development">
<meta property="og:description" content="EGRET">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-53797708-7"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-53797708-7');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">EGRET</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.0.4.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/EGRET.html">Introduction</a>
</li>
<li>
  <a href="../reference/index.html">Function Help Pages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Enhancements.html">Enhancements</a>
    </li>
    <li>
      <a href="../articles/WRTDSK.html">WRTDS-K In Development</a>
    </li>
    <li>
      <a href="../articles/Making%20WRTDS_K%20flux%20estimates.html">WRTDS-K Blog Article</a>
    </li>
    <li>
      <a href="../articles/parallel.html">Running in Parallel</a>
    </li>
    <li>
      <a href="../articles/rResid.html">Random Residuals</a>
    </li>
    <li>
      <a href="../articles/SeasonalFraction.html">Seasonal Analysis</a>
    </li>
    <li>
      <a href="../articles/streamflow_trend.html">Daily Streamflow Trends</a>
    </li>
    <li>
      <a href="../articles/TrendsByMonth.html">Trends by month</a>
    </li>
  </ul>
</li>
<li>
  <a href="../articles/References_WRTDS.html">Bibliograpy</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/USGS-R/EGRET">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="WRTDSK_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>WRTDS-K In Development</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/USGS-R/EGRET/blob/master/vignettes/WRTDSK.Rmd"><code>vignettes/WRTDSK.Rmd</code></a></small>
      <div class="hidden name"><code>WRTDSK.Rmd</code></div>

    </div>

    
    
<p>Important note! This is a work-in-progress. No future behavior on new functions are promised based during this development phase.</p>
<p>In order to run these functions, you will need to install the development version of <code>EGRET</code>. This can be done using the <code>remotes</code> package:</p>
<div class="sourceCode" id="cb1"><pre class="downlit">
<span class="kw">remotes</span>::<span class="fu"><a href="https://remotes.r-lib.org/reference/install_github.html">install_github</a></span>(<span class="st">"USGS-R/EGRET"</span>)
</pre></div>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This document provides a basic set of instructions for calculating WRTDS_K estimates of both concentration and flux (or “load”). It will not give the background or motivation for WRTDS_K. There are now two published papers that lay out the motivation for using this approach, describe the mathematics, and show the results compared to other methods. Those two publications can be found at: <a href="https://pubs.er.usgs.gov/publication/sir20195084" class="uri">https://pubs.er.usgs.gov/publication/sir20195084</a> and <a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025338" class="uri">https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025338</a> .</p>
<p>The most important thing to know is that these are intended for use for providing the best possible estimates of the actual fluxes on each day, or month, or season, or year in the record. They are not intended for use in evaluating trends (which we would do using flow-normalized flux).</p>
</div>
<div id="what-one-needs-in-order-to-run-this-are-the-following-items" class="section level2">
<h2 class="hasAnchor">
<a href="#what-one-needs-in-order-to-run-this-are-the-following-items" class="anchor"></a>What one needs, in order to run this are the following items:</h2>
<ul>
<li>Install the development version of <code>EGRET</code> via the <code>remotes</code> package (see above).</li>
<li>A data set which must already be in the form of an EGRET workspace containing an eList that has all four components of an <strong>eList (INFO, Daily, Sample, surfaces)</strong>. That is, it must be the data and a WRTDS model based on that data that is already estimated. The data set must be in the form of an “.RData” file that contains an <strong>eList</strong>, Nothing else needs to be in that file but if there is other stuff, that’s ok. The discussion and example shown here is carried out on a data set that contains no censored data (“less than values”) and it never has more than one observation on a given day. The description of the method and the examples run in the two papers mentioned are this kind of data set. In the last section of this vignette there will be an explanation of how the method has been generalized to handle these two special cases. The software presented here is able to properly handle data sets that have either or both of these properties (censoring and multiple observations per day).</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="kw"><a href="https://pubs.usgs.gov/tm/04/a10">EGRET</a></span>)

<span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span>(<span class="st">"rockCr.tp.RData"</span>) 
<span class="co"># now we will run the WRTDS_K estimation (using the defaults for now)</span>
<span class="kw">eList_K</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/WRTDS_K.html">WRTDS_K</a></span>(<span class="kw">eList</span>)
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(<span class="kw">eList_K</span><span class="op">$</span><span class="kw">Daily</span>))
</pre></div>
<pre><code>##       Date                  Q                 Julian          Month       
##  Min.   :2006-01-01   Min.   : 0.001699   Min.   :56978   Min.   : 1.000  
##  1st Qu.:2009-03-09   1st Qu.: 0.024352   1st Qu.:58142   1st Qu.: 3.000  
##  Median :2012-05-16   Median : 0.053094   Median :59306   Median : 6.000  
##  Mean   :2012-05-16   Mean   : 0.177447   Mean   :59306   Mean   : 6.435  
##  3rd Qu.:2015-07-24   3rd Qu.: 0.129974   3rd Qu.:60469   3rd Qu.: 9.000  
##  Max.   :2018-09-30   Max.   :16.140602   Max.   :61633   Max.   :12.000  
##                                                                           
##       Day           DecYear        MonthSeq      waterYear   
##  Min.   :  1.0   Min.   :2006   Min.   :1873   Min.   :2006  
##  1st Qu.: 91.0   1st Qu.:2009   1st Qu.:1911   1st Qu.:2009  
##  Median :180.0   Median :2012   Median :1949   Median :2012  
##  Mean   :181.1   Mean   :2012   Mean   :1949   Mean   :2012  
##  3rd Qu.:270.0   3rd Qu.:2016   3rd Qu.:1987   3rd Qu.:2015  
##  Max.   :366.0   Max.   :2019   Max.   :2025   Max.   :2018  
##                                                              
##   Qualifier               i             LogQ              Q7          
##  Length:4656        Min.   :   1   Min.   :-6.378   Min.   :0.003681  
##  Class :character   1st Qu.:1165   1st Qu.:-3.715   1st Qu.:0.034031  
##  Mode  :character   Median :2328   Median :-2.936   Median :0.076759  
##                     Mean   :2328   Mean   :-2.806   Mean   :0.177639  
##                     3rd Qu.:3492   3rd Qu.:-2.040   3rd Qu.:0.178184  
##                     Max.   :4656   Max.   : 2.781   Max.   :3.300126  
##                                                     NA's   :6         
##       Q30                yHat              SE            ConcDay       
##  Min.   :0.007145   Min.   :-2.848   Min.   :0.2977   Min.   :0.06238  
##  1st Qu.:0.049918   1st Qu.:-2.143   1st Qu.:0.3661   1st Qu.:0.12879  
##  Median :0.111814   Median :-1.817   Median :0.4203   Median :0.17797  
##  Mean   :0.178359   Mean   :-1.733   Mean   :0.4572   Mean   :0.26460  
##  3rd Qu.:0.234119   3rd Qu.:-1.468   3rd Qu.:0.5320   3rd Qu.:0.26421  
##  Max.   :1.354904   Max.   : 1.358   Max.   :0.7834   Max.   :5.39851  
##  NA's   :29                                                            
##     FluxDay             FNConc            FNFlux            GenFlux        
##  Min.   :   0.014   Min.   :0.09381   Min.   :  0.4727   Min.   :   0.014  
##  1st Qu.:   0.282   1st Qu.:0.16312   1st Qu.:  1.3266   1st Qu.:   0.284  
##  Median :   0.704   Median :0.23973   Median :  4.0625   Median :   0.681  
##  Mean   :  19.701   Mean   :0.26303   Mean   : 19.3821   Mean   :  17.837  
##  3rd Qu.:   2.699   3rd Qu.:0.33200   3rd Qu.: 14.4545   3rd Qu.:   2.373  
##  Max.   :6929.255   Max.   :0.81444   Max.   :545.3019   Max.   :6936.258  
##                                                                            
##     GenConc      
##  Min.   :0.0500  
##  1st Qu.:0.1217  
##  Median :0.1715  
##  Mean   :0.2482  
##  3rd Qu.:0.2417  
##  Max.   :6.9288  
## </code></pre>
<p>The object being created here is a data frame called <strong>DailyK</strong>. It looks just like <strong>Daily</strong> but with some columns added. What are the extra columns?</p>
<p><strong>trueConc</strong> is the measured concentration on the days when there is a value, many will be NA</p>
<p><strong>trueFlux</strong> (in kg/day) flux for the days when concentration is measured</p>
<p><strong>stdResid</strong> (dimensionless) this is the standardized residual from the WRTDS model estimate, for the days when concentration is measured. It is (ln(trueConc) - yHat) / SE.</p>
<p><strong>yHat</strong> is the WRTDS estimate of the natural log of concentration and SE is the standard error of the WRTDS model for the specific time, discharge, and season.</p>
<p><strong>GenFlux</strong> is the WRTDS_K estimate of the flux for each day (in kg/day) <strong>GenConc</strong> is the WRTDS_K estimate of the concentration for each day (in kg/day)</p>
</div>
<div id="summarizing-results-at-an-annual-time-step" class="section level1">
<h1 class="hasAnchor">
<a href="#summarizing-results-at-an-annual-time-step" class="anchor"></a>Summarizing results at an annual time step</h1>
<p>Now we can take the results from the <strong>DailyK</strong> data frame and compute annual flux values. We will do that for the regular WRTDS and for WRTDS_K (using the data in two columns of <strong>DailyK</strong> the <strong>FluxDay</strong> column and the <strong>GenFlux</strong> column). We can also do these computations for some period of analysis other than the water year, but for now, we will just show the water year computations. The function used is called <strong>computeAnnual</strong> and it produces a data frame called <strong>AnnualResults</strong> and also produces some graphics that show the two types of results. Notice that <strong>AnnualResults</strong> has some attributes that go with it that will tell you what the period of analysis was. They are printed here. Note that the function <strong>computeAnnual</strong> actually does more than the computations, it prints out the content of AnnualResults and it also makes two graphs that tell you some things about how the two types of estimates compare to each other.</p>
<div class="sourceCode" id="cb4"><pre class="downlit">
<span class="kw">AnnualResults</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/setupYears.html">setupYears</a></span>(<span class="kw">eList_K</span><span class="op">$</span><span class="kw">Daily</span>)

<span class="fu"><a href="../reference/WRTDS_K.html">plotWRTDS_K</a></span>(<span class="kw">eList_K</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-2-1.png" width="700"><img src="WRTDSK_files/figure-html/unnamed-chunk-2-2.png" width="700"></p>
<pre><code>##     DecYear          Q      Conc      Flux   ConcDay   FluxDay    FNConc
## 1  2007.247 0.17898031 0.2962950 28.777859 0.2962950 10.503918 0.2983506
## 2  2008.248 0.27055586 0.3516980 44.742356 0.3516980 16.375702 0.2899365
## 3  2009.247 0.26025897 0.3759310 26.165365 0.3759310  9.550358 0.2812448
## 4  2010.247 0.27538327 0.3747984 24.359202 0.3747984  8.891109 0.2729362
## 5  2011.247 0.14896523 0.2471670 14.038737 0.2471670  5.124139 0.2646126
## 6  2012.248 0.08488400 0.1868972  4.034956 0.1868972  1.476794 0.2569138
## 7  2013.247 0.13601784 0.2226408  9.311495 0.2226408  3.398696 0.2517849
## 8  2014.247 0.10545581 0.1980464  8.466954 0.1980464  3.090438 0.2468856
## 9  2015.247 0.20777738 0.2707080 23.161558 0.2707080  8.453969 0.2419903
## 10 2016.248 0.25410346 0.2935102 22.324440 0.2935102  8.170745 0.2372866
## 11 2017.247 0.19541107 0.2342773 33.088650 0.2342773 12.077357 0.2322257
## 12 2018.247 0.09552708 0.1734324  9.414387 0.1734324  3.436251 0.2275343
##      FNFlux   GenConc   GenFlux PeriodLong PeriodStart
## 1  21.65393 0.3035116 11.412228         12          10
## 2  21.04004 0.3027088 14.377783         12          10
## 3  20.46458 0.3822140  9.926332         12          10
## 4  19.90073 0.3130897  7.960983         12          10
## 5  19.35225 0.2414275  4.921882         12          10
## 6  18.83355 0.1980234  1.548080         12          10
## 7  18.42560 0.1978812  2.656734         12          10
## 8  18.02467 0.1976627  3.171315         12          10
## 9  17.63325 0.2217504  6.268860         12          10
## 10 17.25350 0.2302717  5.707152         12          10
## 11 16.88022 0.2421715 10.410761         12          10
## 12 16.52462 0.1714012  3.403874         12          10</code></pre>
<table class="table">
<thead><tr class="header">
<th align="right">DecYear</th>
<th align="right">Q</th>
<th align="right">ConcDay</th>
<th align="right">GenConc</th>
<th align="right">FluxDay</th>
<th align="right">GenFlux</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2007.247</td>
<td align="right">0.1789803</td>
<td align="right">0.2962950</td>
<td align="right">0.3035116</td>
<td align="right">10.503918</td>
<td align="right">11.412228</td>
</tr>
<tr class="even">
<td align="right">2008.248</td>
<td align="right">0.2705559</td>
<td align="right">0.3516980</td>
<td align="right">0.3027088</td>
<td align="right">16.375702</td>
<td align="right">14.377783</td>
</tr>
<tr class="odd">
<td align="right">2009.247</td>
<td align="right">0.2602590</td>
<td align="right">0.3759310</td>
<td align="right">0.3822140</td>
<td align="right">9.550358</td>
<td align="right">9.926332</td>
</tr>
<tr class="even">
<td align="right">2010.247</td>
<td align="right">0.2753833</td>
<td align="right">0.3747984</td>
<td align="right">0.3130897</td>
<td align="right">8.891109</td>
<td align="right">7.960983</td>
</tr>
<tr class="odd">
<td align="right">2011.247</td>
<td align="right">0.1489652</td>
<td align="right">0.2471670</td>
<td align="right">0.2414275</td>
<td align="right">5.124139</td>
<td align="right">4.921882</td>
</tr>
<tr class="even">
<td align="right">2012.248</td>
<td align="right">0.0848840</td>
<td align="right">0.1868972</td>
<td align="right">0.1980234</td>
<td align="right">1.476794</td>
<td align="right">1.548080</td>
</tr>
<tr class="odd">
<td align="right">2013.247</td>
<td align="right">0.1360178</td>
<td align="right">0.2226408</td>
<td align="right">0.1978812</td>
<td align="right">3.398696</td>
<td align="right">2.656734</td>
</tr>
<tr class="even">
<td align="right">2014.247</td>
<td align="right">0.1054558</td>
<td align="right">0.1980464</td>
<td align="right">0.1976627</td>
<td align="right">3.090438</td>
<td align="right">3.171315</td>
</tr>
<tr class="odd">
<td align="right">2015.247</td>
<td align="right">0.2077774</td>
<td align="right">0.2707080</td>
<td align="right">0.2217504</td>
<td align="right">8.453969</td>
<td align="right">6.268860</td>
</tr>
<tr class="even">
<td align="right">2016.248</td>
<td align="right">0.2541035</td>
<td align="right">0.2935102</td>
<td align="right">0.2302717</td>
<td align="right">8.170745</td>
<td align="right">5.707152</td>
</tr>
<tr class="odd">
<td align="right">2017.247</td>
<td align="right">0.1954111</td>
<td align="right">0.2342773</td>
<td align="right">0.2421715</td>
<td align="right">12.077357</td>
<td align="right">10.410761</td>
</tr>
<tr class="even">
<td align="right">2018.247</td>
<td align="right">0.0955271</td>
<td align="right">0.1734324</td>
<td align="right">0.1714012</td>
<td align="right">3.436251</td>
<td align="right">3.403875</td>
</tr>
</tbody>
</table>
<p>The content of <strong>AnnualResults</strong> is fairly obvious.</p>
<p><strong>DecYear</strong> is the mean day of the year for the period of analysis, for example, water year 2007 would have a mean day of 2007.247 (end of March of 2007).</p>
<p><strong>Q</strong> is the mean discharge in m^3/s.</p>
<p><strong>ConcDay</strong> is the mean value of concentration for the year from the regular WRTDS model, in mg/L.</p>
<p><strong>GenConc</strong> is the mean value of concentration for the year from the WRTDS_K model, in mg/L.</p>
<p><strong>FluxDay</strong> is the sum of the daily flux values from the regular WRTDS model, in units of metric tons (same as 10^3 kg).</p>
<p><strong>GenFlux</strong> is the sum of the daily flux values from the WRTDS_K model, in units of metric tons (same as 10^3 kg).</p>
<p>The first graph compares the time series of the two flux records: WRTDS in red and WRTDS_K in green. This graph is fairly typical of what we have seen in a number of studies so far. There are a number of years in which the two estimates are practically identical (e.g. 2011, 2012, 2014) but there are a few cases where they diverge significantly. In this example, in those cases the WRTDS_K estimate is substantially lower than the WRTDS estimate. What that means is that the tendency for WRTDS to predict values that are too high has been reduced. It happens that the flux bias statistic for this data set is 0.35, suggesting that the model has a tendency to estimate fluxes that are too high.</p>
<p>The second graph is just another way to look at these same results, but as a scatter plot of results from the two methods. What we see is a tendency for a fair number of years to plot close to the 1:1 line but four of them are substantially below the line (meaning their WRTDS_K estimates are lower than their WRTDS estimates).</p>
<p>Seeing this, we’d like to dig in a bit and see what’s going on.</p>
</div>
<div id="looking-at-parts-of-the-record-to-see-how-wrtds-and-wrtds_k-are-working" class="section level1">
<h1 class="hasAnchor">
<a href="#looking-at-parts-of-the-record-to-see-how-wrtds-and-wrtds_k-are-working" class="anchor"></a>Looking at parts of the record to see how WRTDS and WRTDS_K are working</h1>
<p>We have a function that produces graphics that show, as a time series, the daily true values (for the days that have samples), the WRTDS estimates for every day, and the WRTDS_K estimates for every day. We could plot the whole record, but the ups and downs of the curves would be so tight that we really couldn’t see what’s going on. So, we let the user pick a time slice to look at. It produces two plots, the first is for concentration (it is typically easier to see what is happening in the estimation with the concentration graphs) and the second is for flux (discharge plays such a big role here that the propagation of error from the concentrations gets somewhat obscured, but flux is, after all, what we are interested in here).</p>
<p>We will look at two examples here, in each case looking at about a half a year. The first one (2018) is a year in which there was very good agreement between the estimates, and the second one (2015) is a year with a large difference between the methods. Let’s see what those results look like.</p>
<div class="sourceCode" id="cb6"><pre class="downlit">
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList_K</span>, start = <span class="fl">2018.2</span>, end = <span class="fl">2018.7</span>, conc = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-3-1.png" width="700"></p>
<div class="sourceCode" id="cb7"><pre class="downlit">
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList_K</span>, start = <span class="fl">2018.2</span>, end = <span class="fl">2018.7</span>, conc = <span class="fl">FALSE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-3-2.png" width="700"></p>
<div class="sourceCode" id="cb8"><pre class="downlit">
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList_K</span>, start = <span class="fl">2015.2</span>, end = <span class="fl">2015.7</span>, conc = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-3-3.png" width="700"></p>
<div class="sourceCode" id="cb9"><pre class="downlit">
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList_K</span>, start = <span class="fl">2015.2</span>, end = <span class="fl">2015.7</span>, conc = <span class="fl">FALSE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-3-4.png" width="700"></p>
<p>What can we learn from these figures? The first, which is a half year in 2018. Note before we start that all of these graphs show either concentration or flux on a log scale. We will start with the concentration graph. We see that there are 7 observed values. When we compare the observed values (red dots) with the WRTDS estimates (black line) for each of those days we see two negative residuals followed by a positive residual a negative a positive and the final two have residuals that are close to zero. Once we get past the second observation (around 2018.25) we see the WRTDS_K curve (in green) going back a forth from being a little above the WRTDS curve to a little below. This alternation indicates that the errors of the model are not ones that persist for very many days and thus the corrections based on these errors don’t persist for very many days. One other thing to note is that the model suggests a big spike in concentration around 2018.4 but there are no samples very close in time to this event (there is a gap of about a month) and the big discharge event took place about half way between these two sample dates. Given this lack of information close to the date of the large flow event, the WRTDS_K will not result in much of a change during this event as compared to what we estimate from WRTDS. The upshot of all of this is that the residuals information doesn’t make much difference during this half year in WRTDS_K results and we really don’t change our estimate by much.</p>
<p>Now, contrast this with the 2015 results. Here we see the first residual being very near zero, but after that every one of them is substantially negative (below the black line). What this is telling us is that something was going on in this part of 2015 such that concentrations were always lower than the WRTDS model (based on the years around 2015, both before and after). We don’t happen to know why this departure exists (perhaps it relates to what tributaries were most active or to something about antecedent conditions). What it does tell us is that generally, throughout the period 2015.35 through 2015.65 it is a good guess that concentrations are likely to have been lower than what the WRTDS model estimates they should be. The math of the WRTDS_K model ends up giving us a green curve that is always below the black curve throughout this period. That means, when the WRTDS_K estimate is summarized for the whole 2015 water year it will be a good deal lower than what WRTDS would give us. Looking at the last of the four graphs (for flux), even though the black and green curves track pretty close to each other the ratio of the two mean fluxes is 0.45. So, the persistant negative residuals causes us to make a major downward adjustment to our estimated flux for the period.</p>
<p>As a generalization we can say that WRTDS_K will result in large adjustments when two things happen: 1) there is a strong persistence of the residuals (long runs of positives or long runs of negatives), and 2) when there are samples collected on or close to the days of maximum flux and they show large absolute residuals.</p>
<p>One final note. These graphs also have an additional bit of information. They say, in their title “Ratio of means is xx”. This ratio is specific to the time slice shown in the plot (not the whole record being estimated) and the ratio stated is WRTDS_K estimate divided by the regular WRTDS estimate.</p>
</div>
<div id="two-options-available-setting-rho-and-setting-niter" class="section level1">
<h1 class="hasAnchor">
<a href="#two-options-available-setting-rho-and-setting-niter" class="anchor"></a>Two options available (setting rho and setting niter)</h1>
<p>One of the things that the user must select is the rho value. We don’t have a strong theoretical basis for selecting the right value of rho, although our research has shown that the results are not highly sensitive to it. In the paper published in Zhang and Hirsch (2019) (see the second URL near the start of this document) we do make some generalizations about the selection of rho. We found that for nitrate a slightly higher rho value (such as 0.95) may be better than for other constitutents such as TP, OrthoP, Suspended Sediment, or Chloride for which values like 0.85 or 0.9 may be better. The somewhat different behavior for nitrate is explained by the fact that at many sites there are some other factors probably related to denitrification the discharge and term does not have a great amount of explanatory power in the WRTDS model. As such, placing more reliance on the results of samples that are close in time is appropriate. One can experiment with different values of rho because it is an argument in the <strong>makeDailyK</strong> function.</p>
<p>We can re-run the analysis with rho of 0.85 and see how much difference it makes. The table shown here lists the ratio the difference in annual values divided by the original annual value (so multiplying these numbers by 100 would result in differences in percent).</p>
<div class="sourceCode" id="cb10"><pre class="downlit">
<span class="kw">eList_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/WRTDS_K.html">WRTDS_K</a></span>(<span class="kw">eList</span>, rho = <span class="fl">0.85</span>)
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(<span class="kw">eList_2</span><span class="op">$</span><span class="kw">Daily</span>,<span class="st">"rho"</span>))
</pre></div>
<pre><code>## [1] 0.85</code></pre>
<div class="sourceCode" id="cb12"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span>(<span class="kw">eList_2</span><span class="op">$</span><span class="kw">Daily</span>,<span class="st">"niter"</span>))
</pre></div>
<pre><code>## [1] 200</code></pre>
<div class="sourceCode" id="cb14"><pre class="downlit">
<span class="kw">AnnualResults2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/setupYears.html">setupYears</a></span>(<span class="kw">eList_2</span><span class="op">$</span><span class="kw">Daily</span>)

<span class="kw">AnnualResults2</span> <span class="op">&lt;-</span> <span class="kw">AnnualResults2</span>[,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]

<span class="kw">Ratios</span> <span class="op">&lt;-</span> (<span class="kw">AnnualResults2</span> <span class="op">-</span> <span class="kw">AnnualResults</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]) <span class="op">/</span> <span class="kw">AnnualResults</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]

<span class="fu"><a href="https://rdrr.io/r/base/row.names.html">row.names</a></span>(<span class="kw">Ratios</span>) <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw">AnnualResults</span><span class="op">$</span><span class="kw">DecYear</span>, <span class="fl">2</span>)
<span class="fu">kable</span>(<span class="kw">Ratios</span>)
</pre></div>
<table class="table">
<thead><tr class="header">
<th align="left"></th>
<th align="right">ConcDay</th>
<th align="right">GenConc</th>
<th align="right">FluxDay</th>
<th align="right">GenFlux</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">2007.25</td>
<td align="right">0</td>
<td align="right">0.0039808</td>
<td align="right">0</td>
<td align="right">0.0063137</td>
</tr>
<tr class="even">
<td align="left">2008.25</td>
<td align="right">0</td>
<td align="right">0.0422655</td>
<td align="right">0</td>
<td align="right">0.0598372</td>
</tr>
<tr class="odd">
<td align="left">2009.25</td>
<td align="right">0</td>
<td align="right">-0.0042541</td>
<td align="right">0</td>
<td align="right">0.0022497</td>
</tr>
<tr class="even">
<td align="left">2010.25</td>
<td align="right">0</td>
<td align="right">0.0580543</td>
<td align="right">0</td>
<td align="right">0.0393209</td>
</tr>
<tr class="odd">
<td align="left">2011.25</td>
<td align="right">0</td>
<td align="right">0.0005039</td>
<td align="right">0</td>
<td align="right">0.0060360</td>
</tr>
<tr class="even">
<td align="left">2012.25</td>
<td align="right">0</td>
<td align="right">-0.0100483</td>
<td align="right">0</td>
<td align="right">0.0034167</td>
</tr>
<tr class="odd">
<td align="left">2013.25</td>
<td align="right">0</td>
<td align="right">0.0253267</td>
<td align="right">0</td>
<td align="right">0.0499078</td>
</tr>
<tr class="even">
<td align="left">2014.25</td>
<td align="right">0</td>
<td align="right">0.0021595</td>
<td align="right">0</td>
<td align="right">0.0067826</td>
</tr>
<tr class="odd">
<td align="left">2015.25</td>
<td align="right">0</td>
<td align="right">0.0509660</td>
<td align="right">0</td>
<td align="right">0.0386905</td>
</tr>
<tr class="even">
<td align="left">2016.25</td>
<td align="right">0</td>
<td align="right">0.0638065</td>
<td align="right">0</td>
<td align="right">0.0799114</td>
</tr>
<tr class="odd">
<td align="left">2017.25</td>
<td align="right">0</td>
<td align="right">-0.0000190</td>
<td align="right">0</td>
<td align="right">0.0450006</td>
</tr>
<tr class="even">
<td align="left">2018.25</td>
<td align="right">0</td>
<td align="right">0.0014377</td>
<td align="right">0</td>
<td align="right">-0.0205527</td>
</tr>
</tbody>
</table>
<p>What we see here is that the change in rho from 0.9 to 0.85 makes less than a 10% difference in any of the years.</p>
<p>Setting the number of iterations to 200 (the default) seems to be sufficient. We can set a different random number seed and see how much difference it makes in the results.</p>
<div class="sourceCode" id="cb15"><pre class="downlit">
<span class="kw">eList3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/WRTDS_K.html">WRTDS_K</a></span>(<span class="kw">eList</span>, seed = <span class="fl">1</span>)
<span class="kw">AnnualResults3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/setupYears.html">setupYears</a></span>(<span class="kw">eList3</span><span class="op">$</span><span class="kw">Daily</span>)
<span class="kw">AnnualResults3</span> <span class="op">&lt;-</span> <span class="kw">AnnualResults3</span>[,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]

<span class="kw">Ratios</span> <span class="op">&lt;-</span> (<span class="kw">AnnualResults3</span> <span class="op">-</span> <span class="kw">AnnualResults</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]) <span class="op">/</span> <span class="kw">AnnualResults</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"ConcDay"</span>, <span class="st">"GenConc"</span>, <span class="st">"FluxDay"</span>, <span class="st">"GenFlux"</span>)]

<span class="fu"><a href="https://rdrr.io/r/base/row.names.html">row.names</a></span>(<span class="kw">Ratios</span>) <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw">AnnualResults</span><span class="op">$</span><span class="kw">DecYear</span>, <span class="fl">2</span>)
<span class="fu">kable</span>(<span class="kw">Ratios</span>)
</pre></div>
<table class="table">
<thead><tr class="header">
<th align="left"></th>
<th align="right">ConcDay</th>
<th align="right">GenConc</th>
<th align="right">FluxDay</th>
<th align="right">GenFlux</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">2007.25</td>
<td align="right">0</td>
<td align="right">-0.0271695</td>
<td align="right">0</td>
<td align="right">-0.0309132</td>
</tr>
<tr class="even">
<td align="left">2008.25</td>
<td align="right">0</td>
<td align="right">-0.0245820</td>
<td align="right">0</td>
<td align="right">-0.0582342</td>
</tr>
<tr class="odd">
<td align="left">2009.25</td>
<td align="right">0</td>
<td align="right">0.0082574</td>
<td align="right">0</td>
<td align="right">0.0161088</td>
</tr>
<tr class="even">
<td align="left">2010.25</td>
<td align="right">0</td>
<td align="right">-0.0053314</td>
<td align="right">0</td>
<td align="right">-0.0064307</td>
</tr>
<tr class="odd">
<td align="left">2011.25</td>
<td align="right">0</td>
<td align="right">0.0065658</td>
<td align="right">0</td>
<td align="right">0.0194969</td>
</tr>
<tr class="even">
<td align="left">2012.25</td>
<td align="right">0</td>
<td align="right">-0.0063160</td>
<td align="right">0</td>
<td align="right">-0.0497557</td>
</tr>
<tr class="odd">
<td align="left">2013.25</td>
<td align="right">0</td>
<td align="right">-0.0121493</td>
<td align="right">0</td>
<td align="right">-0.0252580</td>
</tr>
<tr class="even">
<td align="left">2014.25</td>
<td align="right">0</td>
<td align="right">0.0280695</td>
<td align="right">0</td>
<td align="right">0.0362018</td>
</tr>
<tr class="odd">
<td align="left">2015.25</td>
<td align="right">0</td>
<td align="right">-0.0062751</td>
<td align="right">0</td>
<td align="right">-0.0038074</td>
</tr>
<tr class="even">
<td align="left">2016.25</td>
<td align="right">0</td>
<td align="right">-0.0012663</td>
<td align="right">0</td>
<td align="right">-0.0265826</td>
</tr>
<tr class="odd">
<td align="left">2017.25</td>
<td align="right">0</td>
<td align="right">-0.0057908</td>
<td align="right">0</td>
<td align="right">0.0121248</td>
</tr>
<tr class="even">
<td align="left">2018.25</td>
<td align="right">0</td>
<td align="right">0.0261079</td>
<td align="right">0</td>
<td align="right">0.1646035</td>
</tr>
</tbody>
</table>
<p>This table shows us that, at worst the individual annual fluxes differ by about 11% and many of them differ by less than 2% in successive runs with different seeds The annual concentrations never differ by more than about 2%. This suggests that 200 is a sufficient number of iterations to run to obtain a stable result. For final calculations for publication one might want to specify niter = 500 or niter = 1000 in the call to <strong>makeDailyK</strong>, but the idea here is not perfection, but rather to make a reasonable adjustment of the flux record to account for the serial correlation of the residuals.</p>
</div>
<div id="what-about-putting-these-results-into-the-plotconchist-or-plotfluxhist-graphs" class="section level1">
<h1 class="hasAnchor">
<a href="#what-about-putting-these-results-into-the-plotconchist-or-plotfluxhist-graphs" class="anchor"></a>What about putting these results into the <strong>plotConcHist</strong> or <strong>plotFluxHist</strong> graphs</h1>
<p>Typically when we do some type of trend study we may want to create graphic outputs showing the Flow Normalized values (connected by a line) and the estimated annual values (as dots). If you want to put the WRTDS_K values on these graphs you can use the functions (still in development), setting the argument <code>plotGenConc</code> or <code>plotGenFlux</code> to <code>TRUE</code>.</p>
<p>Here they are being used.</p>
<div class="sourceCode" id="cb16"><pre class="downlit">
<span class="fu"><a href="../reference/plotConcHist.html">plotConcHist</a></span>(<span class="kw">eList_K</span>, plotGenConc = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-6-1.png" width="700"></p>
<div class="sourceCode" id="cb17"><pre class="downlit">
<span class="fu"><a href="../reference/plotFluxHist.html">plotFluxHist</a></span>(<span class="kw">eList_K</span>, plotGenFlux = <span class="fl">TRUE</span>, fluxUnit = <span class="fl">8</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-6-2.png" width="700"></p>
</div>
<div id="operationalizing-this-in-a-batch-job" class="section level1">
<h1 class="hasAnchor">
<a href="#operationalizing-this-in-a-batch-job" class="anchor"></a>Operationalizing this in a batch job</h1>
<p>The process after installing the development version of EGRET.</p>
<ul>
<li>load the workspace for a site</li>
<li>give the command <strong>eList &lt;- WRTDS_K(eList)</strong>
</li>
<li>give the command <strong>AnnualResults &lt;- setupYears(eList)</strong>
</li>
<li>then save the object <strong>AnnualResults</strong>
</li>
<li>plot the results <strong>plotWRTDS_K(eList)</strong>
</li>
<li>the tables and graphs you will probably want can all be made from the content of Annual Results, and the meta data are all in the <strong>INFO</strong> object in the <strong>eList</strong>
</li>
<li>if the interest is in only one season of the year then modify the call to <strong>setupYears</strong> by adding the <strong>paStart</strong> and <strong>paLong</strong> arguments for the season you are interested in.</li>
<li>note that <strong>setupYears</strong> has two attributes that tell the <strong>paStart</strong> and <strong>paLong</strong>, so you can always tell what you used as your period of analysis</li>
</ul>
</div>
<div id="how-the-code-handles-two-kinds-of-special-situations" class="section level1">
<h1 class="hasAnchor">
<a href="#how-the-code-handles-two-kinds-of-special-situations" class="anchor"></a>How the code handles two kinds of special situations</h1>
<p>The description in the two publications mentioned here accurately describes how the computations work in the situation where no days in the record have more than one observed value and where no censored data exist in the record. The following section describes how the code handles data sets that violate one or both of these constraints. You don’t really have to understand this to use the software, but for completeness we are describing how these situations are handled in the code.</p>
<div id="censored-data-less-than-values" class="section level2">
<h2 class="hasAnchor">
<a href="#censored-data-less-than-values" class="anchor"></a>Censored data (less than values)</h2>
<p>In order to fill in estimates for all the days with no samples, we must have a known value on each of the sampled days. We use this known value to compute a residual on the sampled day. These known residuals on either side of a data gap are what initialize the AR(1) process that fills in all the missing values of residuals in the gap. It would be incorrect to set these censored values with the reporting limit (<strong>ConcHigh</strong>) and also incorrect to set these censored values to half the reporting limit (this would be <strong>ConcAve</strong>). The solution is this. Since we are estimating the entire time series of residuals using Monte Carlo simulation we can also use Monte Carlo methods to create an appropriate value for the sampled day. For each replicate of the whole time series we will generate random values for each of the censored sample days. We already have a function that allows us to generate these random realizations of the censored day concentration. It is the function in EGRET called <strong>makeAugmentedSample</strong>. What it does is that on each day with a censored value it defines a truncated log normal distribution and takes a random sample from that distribution to represent the unknown true value on that day. The truncated lognormal distribution is defined by the WRTDS model for that day. It uses estimates of the conditional mean of the log concentration and the conditional standard deviation of the log concentration and assumes that the conditional distribution of the logs is normal. The distribution is not the whole normal distribution, rather it is made up of the left hand tail of the distribution. The truncation point is at the log of the reporting limit for the data value. What this means is that for the censored day, we can create a Monte Carlo sample value of the log of concentration by sampling from that truncated normal distribution (which is specific to the conditions on that day). Note here that the random observation values generated here are NOT used to estimate the WRTDS model; that is done in the usual fashion using the censored sample information.</p>
<p>So now the data generation scheme is done in two phases for each iteration: First we fill in values for each of the censored days and these, combined with the uncensored values constitute the sample data set we will work from. Then we use the AR(1) process to fill in the missing days between all the sampled days. Then when we move on to the next iteration we start all over with estimating all the censored days again and then fill the gaps, etc.</p>
<p>When we plot these data sets using <strong>plotTimeSlice</strong>, when there are censored values they plot in the blue color and they are located on the vertical scale at the reporting limit (meaning that the true value lies somewhere at or below the blue dot).</p>
</div>
<div id="multiple-observations-on-a-day" class="section level2">
<h2 class="hasAnchor">
<a href="#multiple-observations-on-a-day" class="anchor"></a>Multiple observations on a day</h2>
<p>When a day has more than one observation (i.e. more than one sample value) the approach we use here is much the same as what we used in the censored value situation. What we need in order to generate the full WRTDS_K record is a set of unique values for the sampled days. So, for any day with two or more samples we will randomly pick one of them and use it as an end point for the adjacent gap periods. Then once we pick it we generate the values between the sampled days regardless of whether the sample value used is a unique value for that day or if it is randomly selected from the multiple values observed on that day. Then on the next iteration we randomly select the values for these multiply sampled days and proceed with the AR(1) process to fill in between the sampled days. In the plot produced by <code>plotTimeSlice</code> all of the observations are shown as red dots. Thus if there are multiple sample values on a given day they will plot along a vertical line situated on that day.</p>
</div>
<div id="an-example-with-both-special-issues" class="section level2">
<h2 class="hasAnchor">
<a href="#an-example-with-both-special-issues" class="anchor"></a>An example with both special issues</h2>
<div class="sourceCode" id="cb18"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span>(<span class="st">"test.RData"</span>) <span class="co"># the name of your EGRET workspace</span>
<span class="kw">eList</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/WRTDS_K.html">WRTDS_K</a></span>(<span class="kw">eList</span>)
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList</span>, start = <span class="fl">2010.2</span>, end = <span class="fl">2010.4</span>, 
              conc = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
<div class="sourceCode" id="cb19"><pre class="downlit">
<span class="fu"><a href="../reference/WRTDS_K.html">plotTimeSlice</a></span>(<span class="kw">eList</span>, start = <span class="fl">2010.2</span>, end = <span class="fl">2010.4</span>, 
              conc = <span class="fl">FALSE</span>)
</pre></div>
<p><img src="WRTDSK_files/figure-html/unnamed-chunk-7-2.png" width="700"></p>
<p>If we look at the concentration graph we see two things of interest here. Right after 2010.30 there appear to be three days with censored values with a reporting limit at 0.004 mg/L. What is interesting here is that generally the green line (WRTDS_K estimates) go right through the samples (the red dots), here they don’t. That is because in the Monte Carlo simulation to “true” samples generated are always less than the reporting limit (the blue dots) so the green line lies below these points. Also, there is a case at around 2010.38 where there are two data points (red points) that lie one directly above the other. These are two sample values from the same day. The WRTDS_K estimate (green line) goes right between these two sample values because in the Monte Carlo simulation sometimes the sample value is the lower one and sometimes it is the upper one and the result is that the estimate lies between the two.</p>
</div>
</div>
<div id="final-thoughts" class="section level1">
<h1 class="hasAnchor">
<a href="#final-thoughts" class="anchor"></a>Final thoughts</h1>
<p>In a few months we expect to better integrate these WRTDS_K computations into EGRET for a new release of EGRET, but for now (December 2019) this is the way it should be implemented. Feedback is welcome before we more fully integrate it. The citations for the two papers that introduce and experiment with WRTDS_K are as follows.</p>
<p>Lee, C.J., Hirsch, R.M., and Crawford, C.G., 2019, An evaluation of methods for computing annual water-quality loads: U.S. Geological Survey Scientific Investigations Report 2019–5084, 59 p., <a href="https://doi.org/10.3133/sir20195084" class="uri">https://doi.org/10.3133/sir20195084</a>.</p>
<p>Zhang, Q. and Hirsch, R.M., 2019. River water‐quality concentration and flux estimation can be improved by accounting for serial correlation through an autoregressive model. Water Resources Research. <a href="https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019WR025338" class="uri">https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019WR025338</a></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robert Hirsch, Laura DeCicco.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.9000.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
